# [Tensor 생성 및 속성 확인]

# [1] 모듈 로딩 <hr>

In [16]:
import torch
import print_info

[2] 텐서 생성 및 속성 확인 <hr>

# 임의의 값으로 채운 Tensor

In [17]:
torch.manual_seed(12)

# [0,1) 분포 안에서 랜덤 생성
t5 = torch.rand(2,3)

# standard normal 분포안에서 랜덤 생성
t6 = torch.randn(2,3)

t7 = torch.randint(low=1, high=10, size=(2,3))

In [18]:
print_info.print_Tensor_into('t5',t5)
print_info.print_Tensor_into('t6',t6)
print_info.print_Tensor_into('t7',t7)

t5-----------------------
shape  : torch.Size([2, 3])        torch.Size([2, 3])
ndim   : torch.Size([2, 3])        2
device : cpu
dtype  : torch.float32
tensor   : 
tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
t6-----------------------
shape  : torch.Size([2, 3])        torch.Size([2, 3])
ndim   : torch.Size([2, 3])        2
device : cpu
dtype  : torch.float32
tensor   : 
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
t7-----------------------
shape  : torch.Size([2, 3])        torch.Size([2, 3])
ndim   : torch.Size([2, 3])        2
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[8, 4, 6],
        [2, 2, 2]])


In [19]:
import numpy as np
arr = np.linspace(1,10,6)

t1 = torch.from_numpy(arr)			# share 방식
t2 = torch.as_tensor(arr)			# 원본 주소 참조
t3 = torch.tensor(arr)				# copy 방식 : 새로운 메모리 공간 

In [20]:
t1, t2, t3

(tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
        dtype=torch.float64),
 tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
        dtype=torch.float64),
 tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
        dtype=torch.float64))

In [21]:
# 체크
print(f'[전]{arr}')
arr[0] = 5.0
print(f'[후]{arr}')


[전][ 1.   2.8  4.6  6.4  8.2 10. ]
[후][ 5.   2.8  4.6  6.4  8.2 10. ]


In [22]:
# 텐서 체크

print(f't1 =>' ,t1)
print(f't2 =>' ,t2)
print(f't3 =>' ,t3)

t1 => tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t2 => tensor([ 5.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)
t3 => tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
       dtype=torch.float64)


In [24]:
# 생성 Tensor 객체로 값 채운 Tensor 

t0 = torch.tensor([8,9,4])

#t1 = torch.from_numpy(t0)
t1 = torch.as_tensor(t0)
t2 = torch.tensor(t0)

C:\Users\KDT17\AppData\Local\Temp\ipykernel_12492\1492837586.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t2 = torch.tensor(t0)


In [ ]:
# 텐서 원소 변경
print( t0[0], t0[1] )
print(t0[0].item(), t0[1].item())

tensor(8) tensor(9)
8 9


In [28]:
# 텐서 원소 변경
t0[0] =9
print( t0[0], t0[1] )
print(t0[0].item(), t0[1].item())

tensor(9) tensor(9)
9 9


In [30]:
# as_tensor() share 로 원본 변경시 적용 0
# tensor() copy로 원본 변경시 적용x 
print(t1,t2)

tensor([9, 9, 4]) tensor([8, 9, 4])


# [4] 특정데이터 타입의 Tensor 생성 <hr>

In [33]:
t1 = torch.FloatTensor([11,33])
print(t1, t1.dtype, sep='\n')

tensor([11., 33.])
torch.float32


In [32]:
t1 = torch.DoubleTensor([11,33])
print(t1, t1.dtype, sep='\n')

tensor([11., 33.], dtype=torch.float64)
torch.float64


In [ ]:
t1 = torch.BoolTensor([11,0])
print(t1, t1.dtype, sep='\n')

tensor([ True, False])
torch.bool
