# [ Tensor 생성 및 속성 확인]

- Tensor 란?
	* pythorch 에서 데이터 저장 및 모델 입출력 데이터 저장 타입
	* numpy의 ndarray 와 비슷함
	

[1] 모듈로딩 <hr>

In [26]:
import torch

[2] 텐서 생성 - torch.tensor() 함수 <hr>

In [27]:
t1 = torch.tensor(77)					# 0차원 [] X
t2 = torch.tensor([1,3,5])				# 1차원 [] 1개
t3 = torch.tensor([[2,3,4],[9,8,7]])	# 2차원 [[]] 2개
t4 = torch.tensor([[[2,3,4],[9,8,7]]])	# 3차원 [[[]]] 3개
t5 = torch.tensor([[[2,3,4],[9,8,7]],[[9,8,7],[9,8,7]]])	# 3차원 [[[]]] 3개

In [28]:
	# 텐서의 속성 확인
def print_Tensor_into(tname, tobject):
    print(f'{tname}-----------------------')
    print(f'shape  : {tobject.shape}        {tobject.size()}')
    print(f'ndim   : {tobject.shape}        {tobject.dim()}')
    print(f'device : {tobject.device}')
    print(f'dtype  : {tobject.dtype}')
    print(f'tensor   : \n{tobject}')

In [29]:
print_Tensor_into('t1',t1 )
print_Tensor_into('t2',t2 )
print_Tensor_into('t3',t3 )
print_Tensor_into('t4',t4 )
print_Tensor_into('t5',t5 )


t1-----------------------
shape  : torch.Size([])        torch.Size([])
ndim   : torch.Size([])        0
device : cpu
dtype  : torch.int64
tensor   : 
77
t2-----------------------
shape  : torch.Size([3])        torch.Size([3])
ndim   : torch.Size([3])        1
device : cpu
dtype  : torch.int64
tensor   : 
tensor([1, 3, 5])
t3-----------------------
shape  : torch.Size([2, 3])        torch.Size([2, 3])
ndim   : torch.Size([2, 3])        2
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[2, 3, 4],
        [9, 8, 7]])
t4-----------------------
shape  : torch.Size([1, 2, 3])        torch.Size([1, 2, 3])
ndim   : torch.Size([1, 2, 3])        3
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[[2, 3, 4],
         [9, 8, 7]]])
t5-----------------------
shape  : torch.Size([2, 2, 3])        torch.Size([2, 2, 3])
ndim   : torch.Size([2, 2, 3])        3
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[[2, 3, 4],
         [9, 8, 7]],

        [[9, 8, 7],
         [9, 8, 7]]])


In [30]:
t1 = torch.tensor(77, dtype=torch.uint8)					# 0차원 [] X

t2 = torch.tensor([1,3,5],dtype=torch.float16)				# 1차원 [] 1개

t3 = torch.tensor([[2,3,4],[9,8,7]],dtype=torch.int8)		# 2차원 [[]] 2개

t4 = torch.tensor([[[2,3,4],[9,8,7]]])						# 3차원 [[[]]] 3개

t5 = torch.tensor([[[2,3,4],[9,8,7]],[[9,8,7],[9,8,7]]])	# 3차원 [[[]]] 3개

In [31]:
print_Tensor_into('t1', t1)
print_Tensor_into('t2', t2)
print_Tensor_into('t3', t3)
print_Tensor_into('t4', t4)
print_Tensor_into('t5', t5)

t1-----------------------
shape  : torch.Size([])        torch.Size([])
ndim   : torch.Size([])        0
device : cpu
dtype  : torch.uint8
tensor   : 
77
t2-----------------------
shape  : torch.Size([3])        torch.Size([3])
ndim   : torch.Size([3])        1
device : cpu
dtype  : torch.float16
tensor   : 
tensor([1., 3., 5.], dtype=torch.float16)
t3-----------------------
shape  : torch.Size([2, 3])        torch.Size([2, 3])
ndim   : torch.Size([2, 3])        2
device : cpu
dtype  : torch.int8
tensor   : 
tensor([[2, 3, 4],
        [9, 8, 7]], dtype=torch.int8)
t4-----------------------
shape  : torch.Size([1, 2, 3])        torch.Size([1, 2, 3])
ndim   : torch.Size([1, 2, 3])        3
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[[2, 3, 4],
         [9, 8, 7]]])
t5-----------------------
shape  : torch.Size([2, 2, 3])        torch.Size([2, 2, 3])
ndim   : torch.Size([2, 2, 3])        3
device : cpu
dtype  : torch.int64
tensor   : 
tensor([[[2, 3, 4],
         [9, 8, 7]],

 

# [3] 다양한 텐서 생성 함수들 <hr>

In [32]:
t1 = torch.zeros(2,2, dtype=torch.int8)

t2 = torch.ones(2,5, dtype=torch.int8)

t3 = torch.full((2,),4)

t4 = torch.eye(2)

t5 = torch.eye(1,3)


In [33]:
print_Tensor_into('t1',t1)
print_Tensor_into('t2',t2)
print_Tensor_into('t3',t3)
print_Tensor_into('t4',t4)
print_Tensor_into('t5',t5)


t1-----------------------
shape  : torch.Size([2, 2])        torch.Size([2, 2])
ndim   : torch.Size([2, 2])        2
device : cpu
dtype  : torch.int8
tensor   : 
tensor([[0, 0],
        [0, 0]], dtype=torch.int8)
t2-----------------------
shape  : torch.Size([2, 5])        torch.Size([2, 5])
ndim   : torch.Size([2, 5])        2
device : cpu
dtype  : torch.int8
tensor   : 
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int8)
t3-----------------------
shape  : torch.Size([2])        torch.Size([2])
ndim   : torch.Size([2])        1
device : cpu
dtype  : torch.int64
tensor   : 
tensor([4, 4])
t4-----------------------
shape  : torch.Size([2, 2])        torch.Size([2, 2])
ndim   : torch.Size([2, 2])        2
device : cpu
dtype  : torch.float32
tensor   : 
tensor([[1., 0.],
        [0., 1.]])
t5-----------------------
shape  : torch.Size([1, 3])        torch.Size([1, 3])
ndim   : torch.Size([1, 3])        2
device : cpu
dtype  : torch.float32
tensor   : 
tensor([[1., 0., 0.]