# [Tensor Indexing & Slicing]

In [10]:
import torch
import print_info

In [11]:
# 텐서 생성
t1 = torch.linspace(1,10,6)
t1

tensor([ 1.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000])

In [12]:
# 인덱싱
t1[0], t1[-1]

(tensor(1.), tensor(10.))

In [13]:
# 여러개 원소 읽기
t1[[1,-1]]

tensor([ 2.8000, 10.0000])

# [Tensor 연산]

In [14]:
m1 = torch.FloatTensor([[3, 4]]) 
m2 = torch.FloatTensor([[2, 5]])
m3=m1+m2
print(m3, m3.shape)

tensor([[5., 9.]]) torch.Size([1, 2])


In [15]:
m1 = torch.FloatTensor([[1, 2]]) 
m2 = torch.FloatTensor([3])
m3 = m1 + m2
print(m3, m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])


In [16]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])

m3 = m1 +m2
print(m3,m3.reshape)


tensor([[4., 5.],
        [5., 6.]]) <built-in method reshape of Tensor object at 0x000001AFA7194A90>


# 원소 곱셈 mul()  element-wise

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) 
print('Shape of Matrix 2: ', m2.shape)
print( m1 * m2 ) # 2 x 2 
print( m1.mul( m2 ) )

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# [행렬 곱셈] matmul()

In [18]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) 
print('Shape of Matrix 2: ', m2.shape)
m12= m1.matmul( m2 ) 
print( m12.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
torch.Size([2, 1])
