# [Tensor shape 변경]

In [68]:
# 
import torch

In [69]:
# 텐서 생성
t1 = torch.tensor([11,22,33,44,55,66])
t1.shape

torch.Size([6])

In [70]:
# shape 변경 => reshape()
t2 = t1.reshape(-1,1,1)  # 1D => 3D
t2, t2.shape

(tensor([[[11]],
 
         [[22]],
 
         [[33]],
 
         [[44]],
 
         [[55]],
 
         [[66]]]),
 torch.Size([6, 1, 1]))

In [71]:
# t1 1D ==> 4D, t3 저장하기
t3 = t1.reshape(-1,1,1,1)
t3, t3.shape

(tensor([[[[11]]],
 
 
         [[[22]]],
 
 
         [[[33]]],
 
 
         [[[44]]],
 
 
         [[[55]]],
 
 
         [[[66]]]]),
 torch.Size([6, 1, 1, 1]))

In [72]:
# shape 변경 => view()
t2 = t1.view(2,3)

t2, t2.shape

(tensor([[11, 22, 33],
         [44, 55, 66]]),
 torch.Size([2, 3]))

In [73]:
t3 = t1.view(-1,2,3)
t3, t3.shape

(tensor([[[11, 22, 33],
          [44, 55, 66]]]),
 torch.Size([1, 2, 3]))

# [ Axis 변경] 
	* Tensor 의 노멛 정보에서 확인
	* 2D => (m,n) => axis0 m, axis1 n
	* 3D => (l,m,n) => axis0 l, axis1 m, axis2 n


In [74]:
## transpose() 메서드 ======================

t1 = torch.tensor([[11,22,33],[44,55,66]])
t2 = torch.tensor([[[11,22,33],[44,55,66]]])
print(t1.shape, t1 , sep='\n')
print(t2.shape, t2 , sep='\n')


torch.Size([2, 3])
tensor([[11, 22, 33],
        [44, 55, 66]])
torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [44, 55, 66]]])


In [75]:
# 0 번 축 <-> 1번 축
t1.transpose(1,0)


tensor([[11, 44],
        [22, 55],
        [33, 66]])

In [76]:

print( t2.shape, t2, sep='\n', end='\n\n')

# 0 번축 <==> 1번축
t3 = t2.transpose(1,0)
print( t3.shape, t3, sep='\n', end='\n\n')


# 0 번축 <==> 2번축 (1,2,3) ==> (3,2,1)
t4 = t2.transpose(2,0)
print( t4.shape, t4, sep='\n', end='\n\n')

torch.Size([1, 2, 3])
tensor([[[11, 22, 33],
         [44, 55, 66]]])

torch.Size([2, 1, 3])
tensor([[[11, 22, 33]],

        [[44, 55, 66]]])

torch.Size([3, 2, 1])
tensor([[[11],
         [44]],

        [[22],
         [55]],

        [[33],
         [66]]])



In [77]:
# permute() 메서드 =============================
# - 모든 축 axis 변경 가능


In [78]:
# (1,2,3) ==> (2,3,1)
t3 = t2.permute(1,2,0)
print( t3.shape, t3, sep='\n', end='\n\n')

torch.Size([2, 3, 1])
tensor([[[11],
         [22],
         [33]],

        [[44],
         [55],
         [66]]])



# 차원 줄이기 단, 원소 갯수는 유지

In [84]:
# 이미지 1장 => 가로5, 세로 5 , 흑백1 : (5,5,1)
# 형태 : (5,5,1)
# 원소 갯수 : 5*5*1 = 25

t1 = torch.arange(11,36)
t1.shape


torch.Size([25])

In [ ]:
# 1D => 4D
t2 =t1.reshape(1,5,5,1)
t2.shape

torch.Size([5, 5, 1])

In [90]:
# 체널을 제일 앞으로 보내기
t3 =t2.transpose(0,2)
t3

tensor([[[11, 16, 21, 26, 31],
         [12, 17, 22, 27, 32],
         [13, 18, 23, 28, 33],
         [14, 19, 24, 29, 34],
         [15, 20, 25, 30, 35]]])

In [92]:
# 원소 갯수 유지하면서 3D => 2D
t4 = t3.squeeze()
t4.shape

torch.Size([5, 5])

In [ ]:
# 원소 갯수 유지하면서 2D => 3D
t4.unsqueeze(1).shape