[ Custom Model Class 정의 및 설계]
- 데이테셋 및 구현방법에 따른 모델 설계
- 부모클래스 : nn.Module
- 필수 오버라이딩 메서드 : 상속 받은 메서드 중 재정의하는 것
    *  _ _init_ _(self)   : 모델 구조/구성 요소 정의 
    * forward(self, data) : 전방향/순방향 학습 기능 메서드

[1] 모듈 로딩 <hr>

In [2]:
import torch                        # tensor, 내장함수 및 클래스 관련 모듈
import torch.nn as nn               # 인공신경망 관련 층, 함수 클래스 모듈
import torch.nn.functional as F     # 인공신경망 관련 층, AF, LF 함수 모듈

import pandas as pd                 # 데이터 로딩 및 전처리 관련 모듈 
import numpy as np                  # raw 데이터 즉, ndarray 데이터 관련 모듈


[2] 커스텀 모델 클래스 설계 <hr>

In [3]:
## [2-1] 고정된 층과 퍼셉트론 구성 모델
## - 데 이  터 셋 : 피쳐 3 , 타겟 1 , 타겟 연속형
## - 학습    방법 : 지도학습 - 회귀
## - 구현알고리즘 : 인공신경망계열 DNN 
## -------------------------------------------------
##             입력       출력/퍼셉트론수    활성화함수
## - 입력층      3        20                ReLU
## - 은닉층      20       10                ReLU
## - 은닉층      10        5                ReLU
## - 출력층       5        1                 -
## -------------------------------------------------
class CutomModel(nn.Module):
    # 인스턴스 초기화 및 생성 메서드
    def __init__(self):
        super().__init__()
        # ANN 층 인스턴스 생성
        print('__init__()')
        self.in_layer=nn.Linear(3, 20)
        self.hd_layer1=nn.Linear(20, 10)
        self.hd_layer2=nn.Linear(10, 5)
        self.out_layer=nn.Linear(5, 1)

    # 순전파 학습 메서드 
    def forward(self, data):
        #- 입력층
        out=self.in_layer(data)      # data * weight + b
        out=F.relu(out)              # AF(data * weight + b) 결과물

        #- 은닉층1
        out=self.hd_layer1(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물        

        #- 은닉층2
        out=self.hd_layer2(out)      # out * weight + b
        out=F.relu(out)              # AF(out * weight + b) 결과물    

        #- 출력층 : 회귀로 결과 그래도 반환
        out=self.out_layer(out)      # out * weight + b

        return out 
               

In [4]:
## - 모델 사용 -----------------------------------
## 모델 인스턴스 생성 
model=CutomModel()

## 모델 구조 확인
print(model)

__init__()
CutomModel(
  (in_layer): Linear(in_features=3, out_features=20, bias=True)
  (hd_layer1): Linear(in_features=20, out_features=10, bias=True)
  (hd_layer2): Linear(in_features=10, out_features=5, bias=True)
  (out_layer): Linear(in_features=5, out_features=1, bias=True)
)


In [5]:
## 모델 동작 테스트
data=torch.FloatTensor([[10,5,8],[5,9,7]])
print(data)

## 모델에 데이터 전달
pre=model(data)

tensor([[10.,  5.,  8.],
        [ 5.,  9.,  7.]])


In [8]:
model

CutomModel(
  (in_layer): Linear(in_features=3, out_features=20, bias=True)
  (hd_layer1): Linear(in_features=20, out_features=10, bias=True)
  (hd_layer2): Linear(in_features=10, out_features=5, bias=True)
  (out_layer): Linear(in_features=5, out_features=1, bias=True)
)

In [7]:
# 모델 파라미터들 
for name, param in model.named_parameters():
	print(f'name {name} \n param : {param}')

name in_layer.weight 
 param : Parameter containing:
tensor([[-0.1166,  0.2978,  0.4390],
        [ 0.1826,  0.0321, -0.4352],
        [ 0.4761,  0.2141,  0.0142],
        [-0.2006, -0.1758, -0.1752],
        [ 0.0704,  0.3285, -0.1132],
        [-0.0736, -0.4304,  0.4356],
        [-0.1000, -0.1829,  0.1524],
        [-0.4926,  0.4136, -0.5263],
        [ 0.1803,  0.2404,  0.3475],
        [ 0.5433, -0.4335,  0.2613],
        [-0.5768,  0.5075,  0.4338],
        [ 0.1950,  0.3221, -0.2707],
        [-0.0336,  0.1601, -0.2395],
        [ 0.2173,  0.3138,  0.2666],
        [ 0.1504,  0.4442,  0.0141],
        [-0.1757, -0.4151,  0.5208],
        [-0.2642, -0.0772, -0.2487],
        [ 0.2369, -0.0991,  0.2542],
        [ 0.2441, -0.2881, -0.4835],
        [-0.3112, -0.4059,  0.1102]], requires_grad=True)
name in_layer.bias 
 param : Parameter containing:
tensor([ 0.1669, -0.1822, -0.5702, -0.2276, -0.2437, -0.3905,  0.4460, -0.4990,
         0.0183, -0.3961,  0.3819, -0.2356, -0.3670, -0