# [Linear Layer]
-	pytorch 에서 퍼셉트론의 가중치 합계 (Weighed Sum)을 계산해주는 층 클래스
-	출력값에 활성화 함수 (AF) 적용해야 출력값이 됨

[1] 모듈로딩 <hr>

In [ ]:
# 모듈로딩

import torch 					# 텐서관련 모듈
import torch.nn as nn			# 신경망 관련 모듈
import torch.nn.functional as F # 활성화 및 신경망 관련 함수들 

In [3]:
# 임시 데이터 준비

# 2행 3열
X_train = torch.randn(2,3)
y_train = torch.randint(1,5,(2,1))


In [4]:
print(X_train.shape, y_train.shape)

torch.Size([2, 3]) torch.Size([2, 1])


[2] 선형 결합층(Full- Connected Layer : FC Layer)

In [10]:
# 인스턴스 생성

# 입력 피쳐수, 출력 결과 수, 퍼셉트론 수
layer = nn.Linear(3,5)

In [11]:
# 가중치의 합
output = layer(X_train)		# 입력 (2,3)
print(output)

tensor([[ 1.2551,  0.3219, -0.6176, -0.4988, -0.5417],
        [-0.2818, -0.4477,  1.4151,  0.0484,  0.6634]],
       grad_fn=<AddmmBackward0>)


In [12]:
#  W,b  텐서 확인
print(f'weight => {layer.weight}')
print(f'bias => {layer.bias}')

weight => Parameter containing:
tensor([[-0.0924,  0.2430,  0.4921],
        [ 0.5732, -0.1606, -0.2245],
        [-0.3668,  0.1458, -0.3488],
        [ 0.3623, -0.5684, -0.3311],
        [-0.0583,  0.5661, -0.4850]], requires_grad=True)
bias => Parameter containing:
tensor([ 0.4787,  0.3093,  0.1374, -0.0563,  0.0592], requires_grad=True)
