# [Custom Model Class 정의 및 설계]

In [1]:
import torch 				# tensor , 내장함수 및 클래스 관련모듈
import torch.nn as nn		# 인공신경망 관련층 , 함수 클래스 모듈
import torch.nn.functional as F # 인공신경마 관련층 , AF, LF 함수 모듈

import pandas as pd
import numpy as np


[2] 커스텀 모델 클래스 설계 <hr>


In [2]:
# [2-1] 고정된 층 과 퍼셉트론 구성 모델
# - 데이터 셋 : 피쳐 3, 타겟1, 타겟 연속형
# - 학습 방법 : 지도학습 - 회귀
# - 구현 알고리즘 : 인공신경망 계열 DNN

# ----------------------------------------------------
# - 입력층		3		20		ReLu
# -	은닉층		20		10		ReLu
# - 은닉층		10		5		ReLu
# - 출력층 		5		1		-

# -----------------------------------------------------

class CutomModel(nn.Module):
	# 인스턴스 초기화 및 생성 메서드
	def __init__(self):
		super().__init__()
		# ANN 층 인스턴스 생성
		print('__init__()')
		self.in_layer = nn.Linear(3,20)
		self.hd_layer1 = nn.Linear(20,10)
		self.hd_layer2 = nn.Linear(10,5)
		self.out_layer = nn.Linear(5,1)

	# 순전파 학습 메서드
	def forward(self, data):
		# - 입력파	
		out = self.in_layer(data)	# data * weight + b
		out = F.relu(out)			# AF(data * weight +b ) 결과물
	
		# -	은닉층 1
		out = self.hd_layer1(out) 	# out * weight + b
		out = F.relu(out) 			# AF(out* weight + b) 결과물

		# - 은닉층 2
		out = self.hd_layer2(out)	# out * weight + b
		out = F.relu(out) 			# AF(out* weight + b)  결과물

		# - 출력층 : 회귀로 결과 그래도 반환
		out = self.out_layer(out) 	# out * weight +b

		return out
 	

In [3]:
# 모델 사용 ---------------------
# 모델 인스턴스 생성

model = CutomModel()

# 모델 구조확인
print(model)

__init__()
CutomModel(
  (in_layer): Linear(in_features=3, out_features=20, bias=True)
  (hd_layer1): Linear(in_features=20, out_features=10, bias=True)
  (hd_layer2): Linear(in_features=10, out_features=5, bias=True)
  (out_layer): Linear(in_features=5, out_features=1, bias=True)
)


In [5]:
# 모델 동작 테스트

data = torch.FloatTensor([[10,5,8],[5,9,7]])
print(data)

# 모델에 데이터 전달
pre = model(data)
print(pre)

tensor([[10.,  5.,  8.],
        [ 5.,  9.,  7.]])
tensor([[-0.8155],
        [-0.9668]], grad_fn=<AddmmBackward0>)


In [6]:
# 모델 파라미터들 
for name, param in model.named_parameters():
	print(f'name {name} \n param : {param}')

name in_layer.weight 
 param : Parameter containing:
tensor([[-0.0877, -0.1941,  0.5022],
        [-0.4720, -0.3284, -0.2081],
        [-0.3587,  0.4546,  0.5649],
        [-0.1108,  0.5057,  0.5038],
        [ 0.1439, -0.4537, -0.1858],
        [ 0.2784, -0.2508, -0.3708],
        [ 0.1028, -0.5688, -0.1431],
        [-0.2823,  0.4721, -0.0042],
        [-0.2527, -0.1524,  0.3364],
        [ 0.0295,  0.0668,  0.1076],
        [ 0.5700, -0.0867, -0.0198],
        [ 0.1317,  0.3540,  0.4791],
        [-0.1820,  0.4822, -0.4980],
        [-0.2612,  0.3333, -0.0756],
        [ 0.3351,  0.5355, -0.2505],
        [ 0.3259,  0.0902, -0.2044],
        [ 0.1651, -0.1112,  0.0284],
        [-0.1238, -0.0542, -0.2706],
        [ 0.1938, -0.0888, -0.1336],
        [ 0.0390,  0.3418,  0.0514]], requires_grad=True)
name in_layer.bias 
 param : Parameter containing:
tensor([-0.3833,  0.3109,  0.4466,  0.0511,  0.1169,  0.1642,  0.1848,  0.5760,
         0.4213, -0.0964, -0.3597,  0.2406,  0.4799, -0