# [Tensor 의 Storage]
-	메모리에 원소/요소가 저장된 정보및 데이터 가지는 속성

In [42]:
# 모듈 로딩
import numpy as np
import torch 

In [43]:
# 텐서 생성
t1 = torch.tensor([[11,22,33,44,55],[66,77,88,99,00]])

In [44]:
def printStorage(obj, obj_name):
	print(f'\n ======={obj_name} 기본정보 ======')
	print(f'Shape	{obj.shape}')
	print(f'Dim		{obj.ndim}D')
	print(f'Dtype	{obj.dtype}')
	print(f'itemsize{obj.itemsize}')
	print(f'======= STORAGE ======')
	print('Offset', obj.storage_offset())
	print('Stride', obj.stride())
	print(obj)
	print(f'========================')
	print(obj.untyped_storage())

In [45]:
# 메모리 저장 정보 
printStorage(t1, 't1')


 =======t1 기본정보 ======
Shape	torch.Size([2, 5])
Dim		2D
Dtype	torch.int64
itemsize8
======= STORAGE ======
Offset 0
Stride (5, 1)
tensor([[11, 22, 33, 44, 55],
        [66, 77, 88, 99,  0]])
 11
 0
 0
 0
 0
 0
 0
 0
 22
 0
 0
 0
 0
 0
 0
 0
 33
 0
 0
 0
 0
 0
 0
 0
 44
 0
 0
 0
 0
 0
 0
 0
 55
 0
 0
 0
 0
 0
 0
 0
 66
 0
 0
 0
 0
 0
 0
 0
 77
 0
 0
 0
 0
 0
 0
 0
 88
 0
 0
 0
 0
 0
 0
 0
 99
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 80]


* 텐서 형태변경

In [46]:
t2 = t1.reshape(5,-1)
printStorage(t2,'t2')


 =======t2 기본정보 ======
Shape	torch.Size([5, 2])
Dim		2D
Dtype	torch.int64
itemsize8
======= STORAGE ======
Offset 0
Stride (2, 1)
tensor([[11, 22],
        [33, 44],
        [55, 66],
        [77, 88],
        [99,  0]])
 11
 0
 0
 0
 0
 0
 0
 0
 22
 0
 0
 0
 0
 0
 0
 0
 33
 0
 0
 0
 0
 0
 0
 0
 44
 0
 0
 0
 0
 0
 0
 0
 55
 0
 0
 0
 0
 0
 0
 0
 66
 0
 0
 0
 0
 0
 0
 0
 77
 0
 0
 0
 0
 0
 0
 0
 88
 0
 0
 0
 0
 0
 0
 0
 99
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 80]


* 축(axis) 변경

In [ ]:
# t1 (2,5) ==> t1(5,2)
t2 = t1.transpose(0,1)
printStorage(t2,'t2')
print(t2)



 =======t2 기본정보 ======
Shape	torch.Size([5, 2])
Dim		2D
Dtype	torch.int64
itemsize8
======= STORAGE ======
Offset 0
Stride (1, 5)
tensor([[11, 66],
        [22, 77],
        [33, 88],
        [44, 99],
        [55,  0]])
 11
 0
 0
 0
 0
 0
 0
 0
 22
 0
 0
 0
 0
 0
 0
 0
 33
 0
 0
 0
 0
 0
 0
 0
 44
 0
 0
 0
 0
 0
 0
 0
 55
 0
 0
 0
 0
 0
 0
 0
 66
 0
 0
 0
 0
 0
 0
 0
 77
 0
 0
 0
 0
 0
 0
 0
 88
 0
 0
 0
 0
 0
 0
 0
 99
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 80]
tensor([[11, 66],
        [22, 77],
        [33, 88],
        [44, 99],
        [55,  0]])


In [ ]:
# tensor 형태 변경
# t2.view(-1,10) ## => 연속성이 깨져서 생긴 오류
print(t2.is_contiguous())

t2 =t2.contiguous() # 새롭게 생성

print(t2.is_contiguous())
t2.view(-1,10)

True
True


tensor([[11, 22, 33, 44, 55, 66, 77, 88, 99,  0]])