#### [ TEST - TENSOR ]

In [2]:
## 모듈로딩
import torch 
import numpy as np 

[1] 10 ~ 100 사이 5.5 간격의 데이터로 구성된 3차원 텐서 생성하세요.

In [5]:
t1 = torch.arange(10,100,5.5)
t1.reshape(-1,1,1)

tensor([[[10.0000]],

        [[15.5000]],

        [[21.0000]],

        [[26.5000]],

        [[32.0000]],

        [[37.5000]],

        [[43.0000]],

        [[48.5000]],

        [[54.0000]],

        [[59.5000]],

        [[65.0000]],

        [[70.5000]],

        [[76.0000]],

        [[81.5000]],

        [[87.0000]],

        [[92.5000]],

        [[98.0000]]])

[2] 정규분포를 띠는 2D 랜덤 텐서를 생성하세요.(매번 동일한 랜덤값 유지)

In [7]:
torch.manual_seed(42)
t2 = torch.randn((2,2))
t2

tensor([[0.3367, 0.1288],
        [0.2345, 0.2303]])

[3] 임의의 정수값으로 구성된 3차원 텐서를 아래 조건 만족하도록 생성하세요.
- 조건
    * 형태 : 10행 10열 3개
    * 타입 : 0 ~ 255값 저장되는 최소 크기 타입
    * 생성 후 3개 2D 텐서로 분리 저장

In [21]:
import numpy as np

tensor = np.random.rand(3, 10, 10)  # (3, 10, 10) 텐서 생성

# 첫 번째 차원 기준으로 나누기 (각각 (10, 10) 형태)
splits = [tensor[i, :, :] for i in range(tensor.shape[0])]  # 첫 번째 차원 기준으로 분리
print([split.shape for split in splits])  # 출력: [(10, 10), (10, 10), (10, 10)]

[(10, 10), (10, 10), (10, 10)]


In [26]:

t3 = torch.randint(0,256,(3,10,10) ,dtype=torch.uint8 )


# 2. 생성된 텐서를 첫 번째 차원 기준으로 2D 텐서 3개로 분리
split_tensors = [t3[i, :, :] for i in range(t3.shape[0])]

# 출력: 생성된 텐서와 분리된 2D 텐서들 확인
print("전체 3D 텐서 (3, 10, 10):")
print(tensor)

print("\n분리된 2D 텐서들:")
for idx, split_tensor in enumerate(split_tensors):
    print(f"2D 텐서 {idx+1} (10, 10):")
    print(split_tensor)


전체 3D 텐서 (3, 10, 10):
[[[0.85084189 0.147604   0.71531435 0.62879463 0.9026302  0.1176856
   0.43097435 0.87177158 0.7687707  0.40061877]
  [0.337726   0.87156615 0.70785847 0.10202322 0.34845053 0.618325
   0.6840533  0.02977475 0.59208338 0.99532475]
  [0.63780321 0.75674095 0.00301729 0.59491702 0.96724932 0.92866047
   0.74886654 0.31790469 0.72389077 0.61512746]
  [0.34472625 0.04713617 0.99385878 0.01225944 0.09306527 0.90302258
   0.88483302 0.14758103 0.04638633 0.55999125]
  [0.12796458 0.48107881 0.05786957 0.16418535 0.23168176 0.65169505
   0.03546594 0.49518587 0.73389793 0.49592802]
  [0.50225567 0.01415257 0.5591248  0.82077688 0.38208649 0.49691359
   0.64329805 0.2875125  0.91557855 0.4079631 ]
  [0.42885111 0.23273498 0.46923919 0.38308259 0.26205274 0.58946477
   0.10408134 0.88519128 0.35337599 0.60562873]
  [0.24022362 0.10197667 0.58641219 0.95846798 0.8529307  0.71547947
   0.40453454 0.85052241 0.26533829 0.91195625]
  [0.59434454 0.41108069 0.51453431 0.2724158

[4] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 형변환으로 2D 텐서 생성 T2
- T1의 형변환으로 3D 텐서 생성 T3
- T1의 형변환으로 4D 텐서 생성 T4

In [40]:
t1 =torch.Tensor(range(3,37,3))
t2 = t1.reshape(3,4)
t2.shape
t3 = t1.reshape(2,3,2)
t3
t4 = t1.reshape(1,2,3,2)
t4

tensor([[[[ 3.,  6.],
          [ 9., 12.],
          [15., 18.]],

         [[21., 24.],
          [27., 30.],
          [33., 36.]]]])

[5] 아래 2개 텐서에 대한 연산 수행 결과 출력하세요.
- t1 :  [[11,22], [33,44]]
- t2 :  [3,4,5]
- 연산 : 덧셈, 뺄셈, 곱셈, 나눗셈 연산자와 메서드

In [41]:
t1 = torch.tensor([[11,22],[33,44]])
t2 = torch.tensor([3,5])

print(f'덧셈 : {t1+t2}')
print(f'뺄셈 : {t1-t2}')
print(f'나눗셈 : {t1/2}')
print(f'곱셈 : {t1*t2}')
print(f'행렬곱셈 : {t1@t2}')

덧셈 : tensor([[14, 27],
        [36, 49]])
뺄셈 : tensor([[ 8, 17],
        [30, 39]])
나눗셈 : tensor([[ 5.5000, 11.0000],
        [16.5000, 22.0000]])
곱셈 : tensor([[ 33, 110],
        [ 99, 220]])
행렬곱셈 : tensor([143, 319])


[6] 텐서의 행렬곱 결과 출력
- t1 : 원소 10개
- t2 : 원소 5개
- 연산: 메서드

In [57]:
t1 = torch.randint(1,10,(10,))
t2 = torch.randint(1,10,(5,))

t1 = t1.reshape(2,5)
t2 = t2.reshape(5,1)

result = torch.matmul(t1,t2)
print(f'행렬 곱 {result}')

행렬 곱 tensor([[120],
        [149]])


[7] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 축 추가로 2D 텐서 생성 T2
- T1의 축 추가로 3D 텐서 생성 T3
- T1의 축 추가로 4D 텐서 생성 T4

- T4의 축 축소로 3D 텐서 생성 T5
- T3의 축 축소로 2D 텐서 생성 T6
- T2의 축 축소로 1D 텐서 생성 T7

In [70]:
t1 = torch.arange(3,37,3)
print(f'텐선 T1 ({t1}')

# T1의 축을 추가하여 2D 텐서 T2 생성
t2 = t1.unsqueeze(0)  # T1의 첫번째 축에 크기 1을 추가하여 2D 텐서로 변환
print(f'텐선 T2 ({t2}')


# T1의 축을 추가하여 3D 텐서 t3 생성
t3 = t1.unsqueeze(0).unsqueeze(0)
print(f'텐선 T3 ({t3}')

# T1의 축을 추가하여 4D 텐서  t4 생성
t4 = t1.unsqueeze(0).unsqueeze(0).unsqueeze(0)
print(f'텐선 T4 ({t4}')

# t4 의 축을 축소하여 3D 텐서 t5 생성
t5 = t4.squeeze(0)
print(f'텐선 T5 ({t5}')

# t3 의 축을 축소하여 2D 텐서 t6 생성

t6 = t3.squeeze(0)
print(f'텐선 T6 ({t6}')


# t2 의 축을 축소하여 1D 텐서 t7 생성
t7 = t2.squeeze(0)
print(f'텐선 T7 ({t7}')




텐선 T1 (tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])
텐선 T2 (tensor([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36]])
텐선 T3 (tensor([[[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36]]])
텐선 T4 (tensor([[[[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36]]]])
텐선 T5 (tensor([[[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36]]])
텐선 T6 (tensor([[ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36]])
텐선 T7 (tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])
