### [ EVENT 처리 - KEYEVENT]
- EVENT : 사용자들의 마우스나 키보드로 발생하는 동작들
- ex) : 마우스 => 클릭, 드래그,마우스 누르기. & 떼기, 더블 클릭
- ex) : 키보드 => 입력한 키 값들 알파벳, 숫자, 기호들 ...
- Event 처리	
	* 이벤트 발생 시 진행하고 동작 코드 작성하는것
	* 개발자가 원하는 기능으로 정의
	

[1] 모듈 로딩 및 데이터 준비 <hr>

In [2]:
# 컴퓨터 비전 모듈
import cv2
# 이미지 데이터 저장 모듈
import numpy as np
# 시각화 모듈 
import matplotlib.pyplot as plt
# 파일,폴더,경로 관련 모듈
import os

In [3]:
# [1-2] 데이터 준비

IMG_DIR = '../image/'
FILE_NAME ='image612x612.jpg'


In [ ]:
# 현재 모든 이미지 파일 리스트

all_items = os.listdir(IMG_DIR)
file_list = []


for item in all_items :
	# 파일 과 폴더 체크 후 파일만 추출
	print(IMG_DIR+item)
	print(os.path.isfile(IMG_DIR+item))

	if os.path.isfile(IMG_DIR+item):
		file_list.append(IMG_DIR+item)

print(f' 이미지 파일 리스트 : {len(file_list)}개 \n{file_list}')



../image/cat.jpg
True
../image/cat_dog
False
../image/copyimage612x612.jpg
True
../image/dog
False
../image/image3.png
True
../image/image612x612.jpg
True
../image/_gray_image.png
True
 이미지 파일 리스트 : 5개 
['../image/cat.jpg', '../image/copyimage612x612.jpg', '../image/image3.png', '../image/image612x612.jpg', '../image/_gray_image.png']
<class 'str'>


[3] 이미지 로딩 <hr>

In [5]:
# 이미지 읽어 오기
# 로딩 : 경로 + 파일명
color_img = cv2.imread( IMG_DIR+FILE_NAME, cv2.IMREAD_COLOR)

In [6]:
# 정보확인

if color_img.size > 0:
	print(f'{ FILE_NAME}')
	print(f'{color_img}\n 형태:{color_img.reshape},\n차원:{color_img.ndim}D')
else:
	print(f'{FILE_NAME}')
	print(f'형태 :{color_img.shape}')

image612x612.jpg
[[[ 2 54  1]
  [ 2 54  0]
  [ 2 54  0]
  ...
  [56 93 31]
  [58 95 33]
  [62 96 35]]

 [[ 2 54  1]
  [ 2 54  0]
  [ 2 54  0]
  ...
  [52 92 27]
  [56 93 29]
  [58 95 31]]

 [[ 3 52  0]
  [ 3 52  0]
  [ 4 54  0]
  ...
  [48 89 22]
  [51 92 25]
  [55 93 27]]

 ...

 [[43 71 18]
  [31 63  8]
  [18 59  0]
  ...
  [23 88  2]
  [23 88  2]
  [23 88  2]]

 [[41 71 12]
  [31 65  4]
  [20 62  0]
  ...
  [26 90  1]
  [26 90  1]
  [26 90  1]]

 [[25 56  0]
  [23 59  0]
  [24 65  0]
  ...
  [27 91  1]
  [27 91  1]
  [27 91  1]]]
 형태:<built-in method reshape of numpy.ndarray object at 0x000002114320AB10>,
차원:3D


[3] 이미지 출력 및 이벤트 체크 <hr>

In [7]:
# 매개변수 (창 타이틀, 이미지데이터)
cv2.imshow(FILE_NAME, color_img)


while True:
	# 창에 대한 사용자 이벤트 처리
	key = cv2.waitKey()

	print(f'key = {key} - {chr(key)}')

	# 특정 키 이벤트에 따른 처리 코드
	if key in  [ord('q'), ord('Q')]:
		cv2.destroyAllWindows()
		break
	elif key in [ord('s'),ord('S')]:
		ret = cv2.imwrite(IMG_DIR+'copy'+FILE_NAME, color_img)
		print(f'저장 여부 : {ret}')

key = 27 - 
key = 49 - 1
key = 27 - 


ValueError: chr() arg not in range(0x110000)