### [ 이미지 체널 분리]
-	opencv 는 이미지 데이터 저장순서가 BGR 
-	채널분리 후 채널별 출력

[1] 모듈 로딩

In [9]:
# 컴퓨터 비전 모듈
import cv2
# 이미지 데이터 저장 모듈
import numpy as np
# 시각화 모듈 
import matplotlib.pyplot as plt
# 파일,폴더,경로 관련 모듈
import os

In [10]:
# [1-2] 데이터 준비

IMG_DIR = '../image/'
FILE_NAME ='image612x612.jpg'

In [11]:
# 이미지 읽어 오기
# 로딩 : 경로 + 파일명
color_img = cv2.imread( IMG_DIR+FILE_NAME, cv2.IMREAD_COLOR)

In [12]:
# 정보확인

if color_img.size > 0:
	print(f'{ FILE_NAME}')
	print(f'{color_img}\n 형태:{color_img.reshape},\n차원:{color_img.ndim}D')
else:
	print(f'{FILE_NAME}')
	print(f'형태 :{color_img.shape}')

image612x612.jpg
[[[ 2 54  1]
  [ 2 54  0]
  [ 2 54  0]
  ...
  [56 93 31]
  [58 95 33]
  [62 96 35]]

 [[ 2 54  1]
  [ 2 54  0]
  [ 2 54  0]
  ...
  [52 92 27]
  [56 93 29]
  [58 95 31]]

 [[ 3 52  0]
  [ 3 52  0]
  [ 4 54  0]
  ...
  [48 89 22]
  [51 92 25]
  [55 93 27]]

 ...

 [[43 71 18]
  [31 63  8]
  [18 59  0]
  ...
  [23 88  2]
  [23 88  2]
  [23 88  2]]

 [[41 71 12]
  [31 65  4]
  [20 62  0]
  ...
  [26 90  1]
  [26 90  1]
  [26 90  1]]

 [[25 56  0]
  [23 59  0]
  [24 65  0]
  ...
  [27 91  1]
  [27 91  1]
  [27 91  1]]]
 형태:<built-in method reshape of numpy.ndarray object at 0x0000021BC4FC0D50>,
차원:3D


In [19]:
import time
# 이미지 체널 분리

img_b, img_g, img_r = cv2.split(color_img)

img_rgb = cv2.merge((img_r,img_g,img_b))


cv2.imshow('[RGB IMAGE] ', img_rgb)
cv2.imshow('[BGR IMAGE]', color_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# cv2.imshow('[Blue Channel]', img_b)
# cv2.imshow('[Green Channel]', img_g)
# cv2.imshow('[Red Channel]', img_r)

# cv2.waitKey()
# #cv2.destroyAllWindows()
# cv2.destroyWindow(f'[Blue Channel]')
# time.sleep(2)
# cv2.destroyWindow(f'[Green Channel]')
# time.sleep(2)
# cv2.destroyWindow(f'[Red Channel]')



In [14]:
print(f'blue channel : {img_b.shape}, {img_b.ndim}D')
print(f'green channel : {img_g.shape}, {img_g.ndim}D')
print(f'red channel : {img_r.shape}, {img_r.ndim}D')

blue channel : (408, 612), 2D
green channel : (408, 612), 2D
red channel : (408, 612), 2D
