## [ Encoder 살펴보기]
-	데이터 전처리시 사용
-	수집 데이터 ==> 수치화 진행

[1] 모듈로딩 <hr>

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder


[2] LabelEncoder <hr>
-	타겟의 레이블을 0 ~ 클래스 -1 범위의 숫자로 변환 

In [2]:
# [예시] 

le = LabelEncoder()	# 라벨 인코더 인스턴스 생성
le.fit([1,2,2,6]) 	# 라벨코더가 변환할 데이터 정보 학습


# 모델 파라미터
print(le.classes_)

[1 2 6]


In [4]:
# 변환하기
le.transform([1,1,6,2,6,6,2,2])

array([0, 0, 2, 1, 2, 2, 1, 1])

In [ ]:
# [예시 -2]
le = LabelEncoder()
le.fit(['paris','paris','tokyo','amsterdam'])

# 모델 파라미터 확인 : str인 경우 알파벳 순으로 정수 라벨링
print(le.classes_)

encoded_y  = le.transform(['paris','tokyo','tokyo'])	# str => int 변환
# 모델 파라미터 확인 : str인 경우 알파벳 순으로 정수 라벨링
print(f'encoded_y: {encoded_y}')


# - 다시 str로 변환
le.inverse_transform(encoded_y)

['amsterdam' 'paris' 'tokyo']
encoded_y: [1 2 2]


array(['paris', 'tokyo', 'tokyo'], dtype='<U9')

[3] OneHotEncoder <hr>

-	범주형 피쳐 중 순서가 의미없는 피쳐의 경우 사용하는 인코더
-	2D 입력

In [16]:
# [예시 -1] 
ohEndoer = OneHotEncoder(sparse_output= False) # sparse_output = False 면 one-hot 결과 반환


ohEndoer.fit([['Femal',2],['Male',1],['Male',3]])

print(f'피처별 카테고리 정보 : {ohEndoer.categories_}')


# 변환
ohEndoer.transform([['Femal',2],['Male',1],['Male',3]])

피처별 카테고리 정보 : [array(['Femal', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]


array([[1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1.]])

In [18]:
# [예시 -2] 
ohEndoer = OneHotEncoder(sparse_output= False, drop='first') # sparse_output = False 면 one-hot 결과 반환
															# drop = 'first' 첫번째 자리값 버림

ohEndoer.fit([['Femal',2],['Male',1],['Male',3]])
print(f'피처별 카테고리 정보 : {ohEndoer.categories_}')


# 변환
ohEndoer.transform([['Femal',2],['Male',1],['Male',3]])

피처별 카테고리 정보 : [array(['Femal', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]


array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 1.]])

In [20]:
#[예시 -3]
ohEndoer = OneHotEncoder(sparse_output= False, 
						 handle_unknown='ignore') # sparse_output = False 면 one-hot 결과 반환
															# drop = 'first' 첫번째 자리값 버림
															# handle_unknown 존재하지 않는 범주 처리

ohEndoer.fit([['Femal',2],['Male',1],['Male',3]])
print(f'피처별 카테고리 정보 : {ohEndoer.categories_}')


# 변환
ohEndoer.transform([['Femal',2],['Male',1],['Male',4]])


피처별 카테고리 정보 : [array(['Femal', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]


array([[1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

[4] OrdinalEncoder <hr>
-	범주형 피쳐 중 순서가 중요한 경우 사용하는 인코더 

In [34]:
# [예시 1]
import numpy as np
# 결측치가 들어 있는 경우에 대한 처리
odEncoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

odEncoder.fit([['Female',2],['Male',1],['Female',3]])
print(f'피쳐별 카테고리 정보 : {odEncoder.categories_}')

odEncoder.transform([['Female',2],['Male',np.nan],['Female',3]])

피쳐별 카테고리 정보 : [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]


array([[ 0.,  1.],
       [ 1., -1.],
       [ 0.,  2.]])