# [ DL CUSTOM MODEL]

### 모듈로딩 <hr>

In [21]:
import torch			# 텐서 기본 함수 내장함수
import torch.nn as nn	# 텐서 인공신경명 관련 층, 함수 클래스 모음
import torch.nn.functional as F # 인공신경망 관련 층, AF, LF 함수 모듈

import pandas as pd
import numpy as np

[1] 환경상황 예측 모델 - 피쳐 : 3개 - 타겟: 연속형

-	피쳐 : 3개
-	타겟 : 연속형 1개
-	학습 : 지도학습 + 타겟
-	알고리즘 : 인공신경망 계열 - DNN

# 모델 클래스 설계

In [ ]:
# # ----------------------------------------------------------------------------------
# # 클래스  이름 : Test_model
# # 부모 클래스 : 없음
# # 모델층 구성		입력신호수		출력신호수		활성화 함수
# # - 입력층:			피쳐 	3개				30개		ReLu	
# # - 은닉층 1층:  		30개			20개		ReLu	
# # - 은닉층 2층:			30개			10개		ReLu
# # - 은닉층 3층:			20개			10개		ReLu
# # - 은닉층 4층: 		10개			 5개		ReLu
# # - 출력층:				 5개			 1개		 -
# # -----------------------------------------------------------------------------------




class Test_Model(nn.Module):

	# 인스턴스 초기화
	def __init__(self):
		super().__init__()
		print('__init__()')
		self.in_layer = nn.Linear(3,3000)
		self.hd_layer1 = nn.Linear(3000,2000)
		self.hd_layer2 = nn.Linear(2000,1500)
		self.hd_layer3 = nn.Linear(1500,1000)
		self.hd_layer4 = nn.Linear(1000,500)
		self.hd_layer5 = nn.Linear(500,150)
		self.hd_layer6 = nn.Linear(150,100)
		self.hd_layer7 = nn.Linear(100,50)
		self.hd_layer8 = nn.Linear(50,25)
		self.hd_layer9 = nn.Linear(25,10)
		self.hd_layer10 = nn.Linear(10,5)
		self.out_layer = nn.Linear(5,1)

	# 학습 즉, 순방향 진행 메서드 forward:필수 오버라이딩 메서드
	# 매개변수 data : 학습용 데이터 전달
	def forward(self,data):
		
		#입력 -> 입력층
		out = self.in_layer(data)			#출력 
		out = F.relu(out)
		

		#은닉층1
		out = self.hd_layer1(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer2(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer3(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer4(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer5(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer6(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer7(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer8(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer9(out)			#1. 
		out = F.relu(out)
		out = self.hd_layer10(out)			#1. 
		out = F.relu(out)

		# 출력층
		out = self.out_layer(out)			#1. 

		return out





# 모델 사용

In [ ]:
# 모델 설계 체크
model = Test_Model()
model(torch.FloatTensor([[22,33,44],[55,66,77],[88,99,00],[11,22,33],[44,55,66]])) #(1,3)

__init__()


tensor([[-0.1388],
        [-0.1389],
        [-0.1389],
        [-0.1385],
        [-0.1389]], grad_fn=<AddmmBackward0>)

# 모델 층 별 파라미터 즉,  W 와 b 

In [24]:
for name, param in model.named_parameters():
	print(f'\n{name}==================')
	print(f'\n{param}==================')


in_layer.weight==================

Parameter containing:
tensor([[ 0.2948, -0.4518, -0.2729],
        [-0.2200, -0.1503,  0.4104],
        [ 0.5595,  0.4747,  0.3261],
        ...,
        [-0.2918,  0.2015,  0.5399],
        [ 0.1728, -0.0373, -0.5164],
        [-0.4228,  0.3835, -0.1882]], requires_grad=True)==================

in_layer.bias==================

Parameter containing:
tensor([-0.2830,  0.4941, -0.3077,  ..., -0.5509, -0.4339, -0.4209],
       requires_grad=True)==================

hd_layer1.weight==================

Parameter containing:
tensor([[ 0.0181, -0.0163, -0.0160,  ..., -0.0100, -0.0084, -0.0151],
        [-0.0002, -0.0145,  0.0081,  ...,  0.0115, -0.0004, -0.0130],
        [-0.0115, -0.0177, -0.0041,  ..., -0.0163,  0.0068, -0.0032],
        ...,
        [ 0.0158, -0.0151,  0.0067,  ...,  0.0140,  0.0002, -0.0098],
        [-0.0097,  0.0004,  0.0180,  ..., -0.0170, -0.0060,  0.0009],
        [ 0.0038, -0.0154,  0.0048,  ...,  0.0160,  0.0106,  0.0143]],
     

# 테스트