Numpy 특징
 * Numerical Python의 약자
 * 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
 * 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
 * 정교한 브로드 캐스팅(broadcastiong) 기능
 * 파이썬의 자료형 list 와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
 * 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편히
 * 데이터 과학 도구에 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [7]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[1],a1[2],a1[3],a1[4])

a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [12]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [15]:
a3 = np.array([[[1,2,3,],[4,5,6],[7,8,9]],
              [[1,2,3,],[4,5,6],[7,8,9]],
              [[1,2,3,],[4,5,6],[7,8,9]]]
              )
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


배열 생성 및 초기화
- zeros() : 모든 요소를 0으로 초기화 

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones() : 모든요소를 1 로 초기화

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full(): 모든요소를 지정한 값으로 초기화 

In [21]:
np.full((3,3), 1.25)

array([[1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25]])

- eye(): 단위행렬(identity matrix) 생성
    * 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- tri(): 삼각행렬 생성 

In [23]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty(): 초기화되지 않은 배열 생성
    * 초기화가 없어서 배열 생성 비용 저렴하고 빠름
    * 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [24]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like() : 지정된 배열과 shape가 같은 행렬 생성
    * np.zeros_like()
    * np.ones_like()
    * np.full_like()
    * np.empty_like()

In [25]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [26]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

생성한 값으로 배열 생성
-   arange() : 정수 범위로 배열 생성

In [28]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace(): 범위 내에서 균등 간격의 배열 생성

In [29]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace(): 범위 내에서 균등간격으로 로그 스케일로 배열생성

In [30]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

랜덤값으로 배열생성

함수
-   speed : 난수 발생을 위한 시드(speed) 지정
-   permutation : 순서를 임의로 바꾸거나 임의의 순열 반환
-   shuffle : 리스트나 배열의 순서를 뒤섞음
-   random : 랜덤한 수의 배열 생성
-   rand : 균등분포에서 표본 추출
-   randint : 주어진 최소/최대 범위의 난수 추출
-   randn : 표준편차가1, 평균값 0 인 정규분포의 표본추출
-   binomial : 이항분포에서 표본 추출
-   normal : 정규분포(가우시안)에서 표본 추출
-   beta : 베타분포에서 표본 추출
-   chisquare : 카이제곱분포에서 표본 추출
-   gamma : 감마분포에서 표본 추출
-   uniform : 균등(0,1) 분포에서 표본 추출 

- random.random(): 랜덤한 수의 배열 생성

In [31]:
np.random.random((3,3))

array([[0.92032744, 0.84752134, 0.56467697],
       [0.23257974, 0.59451119, 0.03346359],
       [0.03535091, 0.80319438, 0.44273153]])

-   random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [33]:
np.random.randint(0,10,(3,3))

array([[3, 6, 7],
       [4, 2, 7],
       [2, 6, 6]], dtype=int32)

-   random.normal() : 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
-   평균 =0, 표준편차 = 1, 3x3 배열

In [34]:
np.random.normal(0, 1, (3,3))

array([[ 0.95341786, -1.81463761,  0.2237768 ],
       [ 1.23608125,  0.80990115, -1.11984729],
       [ 1.48486201, -2.16906272, -0.14873124]])

-   random.rand() : 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성 

In [36]:
np.random.rand(3,3)

array([[0.09538031, 0.8163841 , 0.1161016 ],
       [0.40620511, 0.29696054, 0.34493095],
       [0.63706199, 0.4656148 , 0.81181156]])

-   random.randn() : 표준 정규 분포(standard normal distribution) 를 고려한 랜덤한 수의 배열 생성

In [37]:
np.random.randn(3,3)

array([[-0.24450722,  0.35151504,  0.72042121],
       [ 0.28007712,  0.12202743,  1.13495996],
       [-0.0166092 ,  1.60626091, -0.4232409 ]])

In [39]:
date = np.array('2025-01-01', dtype=np.datetime64)
date

array('2025-01-01', dtype='datetime64[D]')

In [40]:
date + np.arange(12)

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
       '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12'],
      dtype='datetime64[D]')

In [42]:
datetime = np.datetime64('2025-06-01 12:00')
datetime

np.datetime64('2025-06-01T12:00')

In [44]:
datetime = np.datetime64('2025-06-01 12:00:12.35','ns')
datetime

np.datetime64('2025-06-01T12:00:12.350000000')

In [45]:
def array_info(array):
    print(array)
    print('ndim :', array.ndim)
    print('shape :', array.shape)
    print('dtype :', array.dtype)
    print('size :', array.size)
    print('itemsize :', array.itemsize)
    print('nbytes :', array.nbytes)
    print('strides :', array.strides)

In [46]:
array_info(a1)

[4 5 6 4 5]
ndim : 1
shape : (5,)
dtype : int64
size : 5
itemsize : 8
nbytes : 40
strides : (8,)


In [47]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim : 2
shape : (3, 3)
dtype : int64
size : 9
itemsize : 8
nbytes : 72
strides : (24, 8)


In [48]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim : 3
shape : (3, 3, 3)
dtype : int64
size : 27
itemsize : 8
nbytes : 216
strides : (72, 24, 8)


인덱싱(indexing)

In [49]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [51]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [53]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


슬라이싱(Slicing)

-   슬라이싱 구문 : a[start:stop:step]
-   기본값 : start=0,stop=ndim, step=1

In [55]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[0::2])
print(a1[::-1])


[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [58]:
print(a2)
print('\n',a2[1])
print('\n',a2[1,:])
print('\n',a2[:2, :2])
print('\n',a2[1:, ::-1])
print('\n',a2[::-1, ::-1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [4 5 6]

 [4 5 6]

 [[1 2]
 [4 5]]

 [[6 5 4]
 [9 8 7]]

 [[9 8 7]
 [6 5 4]
 [3 2 1]]


불리언 인덱싱(Boolean indexing)
-   배열 각 요소의 선택 여부를 불리언(True or False) 로 지정
-   True 값인 인덱스의 값만 조회   

In [60]:
print(a1)

bi = [False,True,True,False,True]

print(a1[bi])

bi = [True,False,True,True,False]

print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [64]:
print(a2)

bi = np.random.randint(0,2, (3,3), dtype=bool)
print(bi)
print('\n', a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [ True  True False]
 [False False  True]]

 [2 4 5 9]


팬시 인데싱(Fancy Indexing)

In [67]:
print(a1)
print([a1[0],a1[2]])

ind = [0,3]
print(a1[ind])

# 2차원

ind = np.array([[0,1],
                [2,0]])
print(a1[ind])

[4 5 6 4 5]
[np.int64(4), np.int64(6)]
[4 4]
[[4 5]
 [6 4]]


In [69]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])

print(a2[row,col])
print(a2[row,:])
print(a2[:,col])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
