Numpy 를 활용한 데이터 처리
-	입력 데이터 와 타겟 데이터 확인

In [2]:
from sklearn import datasets
import numpy as np


# 붓꽃 데이터셋 로드

iris = datasets.load_iris()

print(f'iris.keys() : {iris.keys()}')
print(f'type {type(iris)}')
# 데이터셋 설명
print(f"{iris.DESCR}")


iris.keys() : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
type <class 'sklearn.utils._bunch.Bunch'>
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76  

NumPy를 활용한 데이터 처리 

In [4]:
X = iris.data # 입력 데이터 (특성)
y = iris.target  # 정답 데이터 (라벨)

print(X.shape) # (150, 4) => 150개의 샘플 , 4개의 특성
print(y.shape) # (150,) => 150개의 라벨
print(np.unique(y)) # [0 1 2] => 3개의 클래스 존재

(150, 4)
(150,)
[0 1 2]


Numpy 로 데이터 슬라이싱

In [5]:
print(X[:5]) # 처음 5개의 샘플 출력
print(y[:5]) # 처음 5개의 라벨 출력


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


Numpy를 활용한 데이터 변환
-	특정 특성만 선택

In [6]:
X_sepal = X[:,:2] # 꽃받침(Sepal) 길이와 너비만 선택
print(X_sepal.shape)

(150, 2)


- 조건필터링

In [8]:
X_setosa = X[y == 0] # 'setosa' 품종의 데이터만 선택
print(X_setosa.shape)

(50, 4)


### Scikit-learn 과 Numpy 를 활용한 머신러닝 예제

(1) 데이터 분할
-	먼저 데이터를 훈련세트( train set) 와 테스트 세트 (test set)로 나눕니다.

In [9]:
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

print(X_train.shape) # (120,4) => 80% 훈련데이터
print(x_test.shape) # (30,4) => 20% 테스트 데이터

(120, 4)
(30, 4)


(2)  머신러닝 모델 학습
-	간단한 호지스틱 회귀(Logistic Regression) 모델을 학습

In [ ]:
from sklearn.linear_model import LogisticRegression