# Numpy & OpenCV

#### [이미지 와 Numpy]

-	OpenCV 에서 이미지나 동영상을 읽어 들이는 함수 cv2.imread()  => Numpy 배열을 반환
-	ndim : 차워(축) 의 수
-	shape : 각 차원의 크기 (튜플)
-	size : 전체 요소의 개수, shape 의 각 항목의 곱
-	dtype : 요소의 데이터 타입
-	itemsize : 각 요소의 바이트크기

-	이미지는 여러개의 픽셀들의 값으로 구성
-	수많은 행과 열로 구성된 픽셀
- 	데이터의 모음

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt


IMG_DIR = './image/'
FILE = IMG_DIR +'cat.jpg'




In [3]:
img = cv2.imread(FILE)
type(img)

numpy.ndarray

ndarray = N 차원 배열
-	즉 다차원 배열을 의미
-	OpenCV 는 기본적으로 이미지 3차원 배열
-	행 X 열 X 채널 로 표현
-	형 X 열 은 이미지의 크기
-	체널은 컬러인 경우 파랑,초록,빨강

In [4]:
# 3 차원
img.ndim

3

In [5]:
# 배열이 629X921
img.shape

(629, 921, 3)

In [6]:
# 전체 요소의 개수 
img.size

1737927

In [7]:
# 이미지 픽셀 데이터는 음수이거나 소수점을 갖는 경우 없음 =>  255 
img.dtype

dtype('uint8')

In [8]:
#  값은 각 요소의 크기가 1바이트
img.itemsize

1

Numpy 배열 생성
-	값을 가지고 생성하는 방법, 크기만 지정해서 생성
-	크기만 지정해서 생성 방법 
=> 다시 특정한 초기 값을 모든 요소에 지정하는 경우
=> 범위를 지정해서 순차적으로 증가 또는 감소하는 값을 갖게 하는 방법


* 값으로 생성 : array()
* 초기 값으로 생성 : empty(), zeros(), ones(), full()
* 기존 배열로 생성 : empty_like(), zeros_like(), full_like()
* 순차적인 값으로 생성 : arange()
* 난수로 생성 : random.rand(), random.randn()

[값으로 생성]
-	배열 생성에서 사용할 값을 가지고 있는경우 numpy.array() 함수로 간단히 생성


* numpy.array(list [, dtype]) : 지정한 값들로 Numpy 배열 생성
* dtype : 데이터 타입 (생략하면 값에 의해 자동 결정)


In [ ]:
a = np.array([1,2,3,4])
print(a)
print(f"타입 : {a.dtype}")
print(f"속성 : {a.shape}")

[1 2 3 4]
타입 : int64
갯수 : (4,)


In [14]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
int64
(2, 4)


In [16]:
# 실수와 정수와 소수점이 있는 실수를 섞어서 배열을 만들면 실수타입
c = np.array([1,2,3.14,4,5])
c

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [18]:
# dtype 을 지정해서 생성해야 할때를 위해서 Numpy생성

a = np.uint8([1,2,3,4,5])
a

array([1, 2, 3, 4, 5], dtype=uint8)

###  [ 크기와 초기 값으로 생성]

-	주로 많이 쓰임
-	배열의 차수 와 크기 그리고 최 값을 지정해서 생성


* numpy.empty(shape [, daype]) : 초기화 되지 않은 (쓰레기 값)으로 배열생성
* shape : 튜플, 배열의 각 차수의 크기 지정
* numpy.zeros(shape [, dtype]): 0 (zero)으로 초기화 된 배열 생성
* numpy.one(shape [, dtype]) : 1로 초기화 된 배열 생성
* numpy.full(shape, fill_value [, dtype]) : fill_value 로 초기화 된 배열 생성

In [22]:
# 2행 3열 배열이 만들어짐
a = np.empty((2,3))

print(a)

[[5.40131448e-038 4.31244563e-033 4.79310040e-037]
 [8.82928589e+169 0.00000000e+000 0.00000000e+000]]


In [23]:
# 어떤 값으로 초기화 함수
# ndarray.fill(value) : 배열의 모든 요소를 value 로 채움

a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [27]:
# 어떤 특정 값으로 모든 요소를 초기화 하는 일 
# 이런 작업을 한번에 해주는 함수 
# zeros(), ones(), full()

b = np.zeros((2,3))
b , b.dtype

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 dtype('float64'))

In [28]:
c = np.zeros((2,3), dtype=np.int8)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [29]:
e = np.full((2,3,4), 255, dtype=np.uint8)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

0 이나 1이 아닌 다른 원하는 초기 값을 지정하고 싶을 때는 앞의 코드처럼 full() 함수를 쓸수 있다.

-	새로운 배열을 생성할때 기존에 있던 배열과 같은 크기의 배열

-	empty_like(array [, dtype]) : 초기화 되지않은 , array 와 같은 shape 와 dtype 의 배열생성
-	zeros_like(array [, dtype]) : 0 으로 초기화된 , array 와 같은 shape 와 dtype 의 배열생성 
-	ones_liek(array [, dtype]) : 1로 초기화된, array 와 같은 shape 와 dtype 의 배열생성
-	full_liek(array, fill_value [, dtype]) : fill_value 로 초기화된 , array 와 같은 shape 와 같은 dtype 배열생성 

In [30]:
img = cv2.imread(FILE)

In [33]:
print( img)
print(f"속성 {img.shape}")
print(f"타입 {img.dtype}")

[[[ 45   1  70]
  [ 45   1  70]
  [ 43   3  68]
  ...
  [219 150   3]
  [220 151   4]
  [219 150   3]]

 [[ 52   5  74]
  [ 48   1  69]
  [ 43   1  66]
  ...
  [217 149   0]
  [217 149   0]
  [218 150   1]]

 [[ 51   2  76]
  [ 49   1  73]
  [ 43   2  64]
  ...
  [219 150   0]
  [219 150   0]
  [218 148   0]]

 ...

 [[126   1 205]
  [130   5 209]
  [128   1 207]
  ...
  [  1   1   1]
  [  1   1   1]
  [  0   0   0]]

 [[124   2 204]
  [128   5 209]
  [127   2 206]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[120   0 202]
  [125   3 205]
  [124   1 205]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
속성 (629, 921, 3)
타입 uint8


In [34]:
a = np.empty_like(img)
b = np.zeros_like(img)
c = np.ones_like(img)
d = np.full_like(img,255)

In [35]:
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [36]:
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [37]:
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       ...,

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=uint8)

In [38]:
d

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

[시퀀스 와 난수로 생성]

-	numpy.arrage([start=0, ] stop [, step =1, dtype=float64]) : 순차적인 값으로 생성

* start: 시작값
* stop : 종료값
* step : 증가값
* dtype : 데이터 타입


* 	numpy.random.rand([d0 [, p...,dn]]) : 0과 1 사이의 무작위 수로 생성
-	d0, d1, ,,,,, dn : shape : 생락하면 난수 한개 반환

* 	numpy.random.randn([d0, [, d1[,,,, dn]]) : 표준 정규분포 (평균 :0 , 분산:1) 를 따르는 무작위수 생성


In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [42]:
c = np.arange(3,9,2)
c

array([3, 5, 7])

arange() 함수는 1차원 배열만을 생성할수 있다.
다차원 배열 , 특히 이미지 데이터를 갖는 3차원 배열로 만들기 위해서는  => 차원 변경

난수를 발생하는 함수 radom.rand() 와 random.randn()

rand() 함수 와 0과 1사이 의 값을 무작위수 

randn() 함수는 평균이 0 이고 분산이 1인 정규 분포를 따르는 무작위수

두 함수 모두 인자 없이 호출하면 난수 1개
원하는 차수(shape)에 맞게 인자를 전달하면 해당 차수에 맞는 배열을 생성

In [43]:
np.random.rand()

0.15645854695393469

In [44]:
np.random.randn()

1.2764051918318968

In [46]:
a = np.random.rand(2,3)
a

array([[0.33182822, 0.80888862, 0.36671225],
       [0.3031669 , 0.06869254, 0.96146416]])

In [47]:
b = np.random.randn(2,3)
b

array([[ 1.06023796,  0.50826373,  0.42742656],
       [ 0.19631483, -0.08387107, -0.41489241]])

[dtype 변경]

-	ndarray.astype(dtype) : dtype 변경하고 싶은 dtype , 문자열, 또는 dtype
-	numpy.uintXX(array) : array를 부호 없는 (정수 uint) 타입으로 변경해서 반환
-	numpy.intXX(array) :array 를 int 타입으로 변경해서 반환
-	numpy.floatXX(array) : array 를 float 타입으로 변경해서 반환
-	numpy.complexXX(array) : array 를 복소수(complex) 타입으로 변경해서 반환 

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
b = a.astype('float32')
b

array([0., 1., 2., 3., 4.], dtype=float32)

In [52]:
a.dtype

dtype('int64')

In [58]:
d = np.uint8(a)
d

array([0, 1, 2, 3, 4], dtype=uint8)

# [ 차원 변경 ]
-	원래는 1차원이던 배열을 2행 3열 배열로 바꾼다던지, 100 X 200 x 3 인 배열을 1차원으로 바꾸는 식의 작업

-	ndarray.reshape(newshape) : ndarray 의 shape 를newshape 로 차원변경
-	numpy.reshape(ndarray, newshape) : ndarray 의 shape 를 newshape 로 차원변경
-	ndarray : 원본 배열 객체
-	newshape : 변경하고자 하는 새로운 shape(튜플)
- 	numpy.ravel(ndarray) : 1차원 배열로 차원 변경
-	ndarray: 변경할 원본 배열
-	ndarray.T : 전치배열

In [59]:
a = np.arange(6)
a 

array([0, 1, 2, 3, 4, 5])

In [61]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
c = np.reshape(a,(2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
d = np.arange(100).reshape(2,-1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [65]:
d.shape

(2, 50)

In [68]:
# -1 의 의미는 해당 차수에 대해서는 크기를 지정하지 않겠다.
e = np.arange(100).reshape(-1,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [69]:
g = np.arange(10).reshape(2,-1)
g

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

[브로드캐스팅 연산]

-	Numpy 배열을 사용하는 가장 큰 이유 브로드캐스팅
-	0 ~9 까지 있는 파이썬 리스트의 모든 항목 값을 1씩 증가 시키려면 반목문
- 	하지만 Numpy 배열에 한번만 연산해도  같은 결과 브로드캐스팅

In [71]:
mylist =list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
for i in range(len(mylist)):
	mylist[i] = mylist[i] +1

print(mylist) 


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [74]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# 브로드캐스팅
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

브로드캐스팅 연산은 모든산술연산 가능

In [77]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a +5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
a - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [80]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [81]:
a /2 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [82]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [83]:
b = np.arange(6).reshape(2,-1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
b*3

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [85]:
b >3

array([[False, False, False],
       [False,  True,  True]])

배열 끼리도 연산 가능

In [86]:
a = np.arange(10,60,10)
b = np.arange(1,6)


In [87]:
a , b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

In [88]:
a + b

array([11, 22, 33, 44, 55])

In [89]:
a - b

array([ 9, 18, 27, 36, 45])

In [90]:
a * b

array([ 10,  40,  90, 160, 250])

In [91]:
a / b

array([10., 10., 10., 10., 10.])

In [92]:
a ** b

array([       10,       400,     27000,   2560000, 312500000])

배열 간의 연산에는 약간의 제약이 있음

-	두배열의 shape 가 완전히 동일하거나 둘중에 하나가 1차원이면서 1차원 배열의 축의 길이가 같아야함

In [95]:
# 두 배열의  shape 가 일치 하지않아서 연산 실패
a = np.ones((2,3))
b = np.ones((3,2))
# a + b

In [96]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
c = np.arange(3)
c

array([0, 1, 2])

In [100]:
# 배열 c 가 1차원이고 1차원 배열의 열의 개수가 a 배열의 열의개수와 같아서 연산이 가능
a + c

array([[1., 2., 3.],
       [1., 2., 3.]])

[인덱싱 과 슬라이싱]

Numpy 배열은 파이썬의 리스트 처럼 인덱스로 각 요소에 접근할수있다.

In [102]:
a = np.arange(10)
a[5]

np.int64(5)

In [107]:
# 3 X 4 
b = np.arange(12).reshape(3,4)
b ,b[1], b[1,2]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([4, 5, 6, 7]),
 np.int64(6))

In [110]:
# 슬라이싱
a  = np.arange(10)
a, a[2:5], a[5:]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([2, 3, 4]),
 array([5, 6, 7, 8, 9]))

In [112]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [117]:
b = np.arange(12).reshape(3,4)
b ,b[2, :], b[0:2,1]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 8,  9, 10, 11]),
 array([1, 5]))

In [120]:
b[0:2,1:3] = 0
bb = b[0:2,1:3]
b, bb

(array([[ 0,  0,  0,  3],
        [ 4,  0,  0,  7],
        [ 8,  9, 10, 11]]),
 array([[0, 0],
        [0, 0]]))

In [123]:

bb[0] = 999
b, bb

(array([[  0, 999, 999,   3],
        [  4,   0,   0,   7],
        [  8,   9,  10,  11]]),
 array([[999, 999],
        [  0,   0]]))

- b[0:2,1] 은 b 배열 0~1행 의 1열 요소들을 의미하고
- b[0:2,1:3] b 배열 0 ~ 1 행의 1~2열 요소들을 의미한다. 

* 만약 파이썬 리스트 처럼 복제본을 얻고 싶다면 ndarray.copy()함수를 명시적으로 호출

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a[[1,3]]

array([1, 3])

In [130]:
a[[True, False,True,False,True]]


array([0, 2, 4])

In [131]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
b = a>5 
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [133]:
a[b]

array([6, 7, 8, 9])

[병합과 분리]

-	2개 이상의 Numpy 배열을 병합하는 방법은 크게 두가지
-	 단순히 배열들을 이어 붙여서 크기를 키우는 방법
-	 새로운 차원을 만들어서 서로서로 끼워 넣은방법

-	numpy.hstack(arrays) : arrays 배열을 수평으로 병합
-	numpy.vstack(arrays) : arrays 배열을 수직으로 병합
-	numpy.concatenate(arrays, axis=0) : arrays 배열을 지정한 축 기준으로 병합
-	numpy.stack(arrays, axis=0): arrays 배열을 새로운 축으로 병합
-	arrays : 병합 대상 배열(튜플)
-	axis : 작업할 대상 축 번호


가장 손쉽게 쓸수 있는 함수 numpy.vstack() 과 numpy.hstack()

In [134]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [135]:
b = np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [ ]:
# 수직으로 병합
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [137]:
# 수평으로 병합
np.hstack((a,b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
# 사용자 지정축 axis =0 
np.concatenate((a,b),0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [139]:
# 사용자 지정축 axis =1
np.concatenate((a,b),1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

numpy.stack() 함수는 차원(축) 이 새로 늘어나는 방법으로 병합
- 축 번호를 지정하지 않으면 0번
- -1은  마지막 축 번호 

In [142]:
a = np.arange(12).reshape(4,3)
b = np.arange(10,130,10).reshape(4,3)

a,b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]))

In [144]:
c = np.stack((a,b), 0)
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [147]:
d = np.stack((a,b), -1)
d

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [148]:
d = np.stack((a,b),1)
d.shape

(4, 2, 3)

In [149]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [151]:
e = np.stack((a,b),2)
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [152]:
e.shape

(4, 3, 2)

In [154]:
ee = np.stack((a,b), -1)
ee.shape

(4, 3, 2)

-	numpy.vsplit(array, indice) : array 배열을 수평으로 분리
-	numpy.hsplit(array, indice) : array 배열을 수직으로 분리
-	numpy.split(array, indice, axis=0) : array 배열을 axis 축으로 분리
-	array : 분리한 배열
-	indice : 분리할 개수 또는 인덱스 
-	axis : 기준 축 번호

-	indince 는 어떻게 나눌지는 정하는 인자인데, 정수 또는 1차원 배열
-	정수 를 배열을 그 수로 나누고, 1차원 배열을 전달 하면, 나누고자 하는 인덱스
-	indice 인자의 사용

In [155]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [157]:
np.hsplit(a,[3,6,9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
np.split(a,3,0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

[ 검색 ]

-	Numpy 배열을 사용하는 이유는 수많은 데이터를 쉽고 빠르게 다루려는 이유

- ret = numpy.where(condition [,t,f]) : 조건에 맞는 요소를 찾기
- condition : 검색에 사용할 조건식
- t, f : 조건에 따라 지정할 값  또는 배열, 배열의 경우 조건에 사용한 배열과 같은 shape 
- t: 조건에 맞는 값에 지정할 값이나 배열
- f:조건에 틀린 값에 지정할 값이나 배열

*	numpy.nonzero(array) : array 에서 요소중에 0 이 아닌 요소의 인덱스를 반환
* 	numpy.all(array [,axis]) : array 모든 요소가 True 인지 검색

-	array :검색 대상 배열
-	axis :검색할 기준 축, 생략하면 모든 요소 검색, 지정하면 축 개수별로 결과 반환

- 	numpy.any(array [, axis]) : array 의 어느 요소이든 Ture 가 있는지 검색

In [159]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [160]:
np.where(a > 15)

(array([6, 7, 8, 9]),)

In [161]:
np.where(a > 15 , 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [162]:
np.where(a > 15 , 99, a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [163]:
np.where(a<15,a,0)

array([10, 11, 12, 13, 14,  0,  0,  0,  0,  0])

In [164]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
coords = np.where(b>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))