#### [ Numpy ndarray의 형태 shape 변환 ]
- shape 변환 : 원소 갯수 유지, 형태만 1D <=> nD 변경
- 함수 : numpy.reshape()
- 메서드 : ndarray.reshape()

In [21]:
##  모듈로딩
import numpy as np 

In [22]:
## ndarray 객체 생성
n1 = np.array([[11,22], [33,44], [55,66]])
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [23]:
## 2D ==> 3D : 원소 갯수는 유지됨
## reshape( shape 정보 )
n1.reshape(1, 3, 2)   # 1 * 3 * 2 == 원래 원소 갯수

array([[[11, 22],
        [33, 44],
        [55, 66]]])

In [24]:
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [8]:
n1.reshape(1, 2, 3)  # 1 * 2 * 3 == 원래 원소 갯수

array([[[11, 22, 33],
        [44, 55, 66]]])

In [9]:
n1.reshape(3, 1, -1)  # 3 * 1 * ? == 원래 원소 갯수

array([[[11, 22]],

       [[33, 44]],

       [[55, 66]]])

In [14]:
n3=n1.reshape(6, 1, -1)  # 6 * 1 * ? == 원래 원소 갯수
print("n3=>", n3.ndim, n3.shape, n3.data, n3.strides)
print("n1=>", n1.ndim, n1.shape, n1.data, n1.strides)

n3=> 3 (6, 1, 1) <memory at 0x000002A81289EB80> (8, 8, 8)
n1=> 2 (3, 2) <memory at 0x000002A812472040> (16, 8)


- 함수 : numpy.resize()
- 메서드: ndarray.reszie()

In [25]:
n1.resize((1,6))
n1

array([[11, 22, 33, 44, 55, 66]])

In [26]:
n1.resize(6,1)
n1

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [29]:
## -> 원소 갯수 변경 
n1.resize(6,2, refcheck=False)
n1

array([[11, 22],
       [33, 44],
       [55, 66],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [30]:
n1.resize(2,1, refcheck=False)
n1

array([[11],
       [22]])