#### [ Numpy ndarray 1D 변환 ]
- flatten() 함수 / 메서드  :  다른 메모리 공간에 저장
- ravel() 함수 / 메서드 : 동일 데이터 메모리 공유

In [45]:
## 모듈 로딩
import numpy as np

In [46]:
## ndarray 객체 
n1 = np.array([[11,22], [33,44], [55, 66]])
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [47]:
## ND => 1D 변환 ==> flatten() 
n1.flatten()

array([11, 22, 33, 44, 55, 66])

In [48]:
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [49]:
n1[0,0] = 100
n1

array([[100,  22],
       [ 33,  44],
       [ 55,  66]])

In [50]:
n11 = n1.flatten()
n11

array([100,  22,  33,  44,  55,  66])

In [51]:
n1[0,0] = 77
n11, n1

(array([100,  22,  33,  44,  55,  66]),
 array([[77, 22],
        [33, 44],
        [55, 66]]))

In [54]:
## ND => 1D 변환 ==> ravel() 
print(n1)

n11=n1.ravel()
print(n11)

[[ 0 22]
 [33 44]
 [55 66]] <memory at 0x0000023DAB2D7520>
[ 0 22 33 44 55 66] <memory at 0x0000023DAB3E14C0>


In [53]:
## 원본 ndarray 데이터 변경 시 ravel() 저장된 데이터도 변경됨!
n1[0,0] = 00
print(n1)
print(n11)

[[ 0 22]
 [33 44]
 [55 66]]
[ 0 22 33 44 55 66]
