#### [ TEST - TENSOR ]

In [5]:
## 모듈로딩
import torch 
import numpy as np 

[1] 10 ~ 100 사이 5.5 간격의 데이터로 구성된 3차원 텐서 생성하세요.

In [14]:
# 10부터 100까지 5.5 간격으로 생성
data = torch.arange(10, 100, 5.5)

# 생성된 데이터를 3차원 텐서로 변경
tensor_3d = data.reshape(-1, 1, 17)  # 3D 텐서로 변환

print(tensor_3d)

tensor([[[10.0000, 15.5000, 21.0000, 26.5000, 32.0000, 37.5000, 43.0000,
          48.5000, 54.0000, 59.5000, 65.0000, 70.5000, 76.0000, 81.5000,
          87.0000, 92.5000, 98.0000]]])


[2] 정규분포를 띠는 2D 랜덤 텐서를 생성하세요.(매번 동일한 랜덤값 유지)

In [18]:
torch.manual_seed(45)
#정규분포 랜덤 값 생성:

#torch.randn()을 사용하여 평균이 0이고 표준편차가 1인 정규분포를 따르는 랜덤 값을 생성합니다.

t2 = torch.randn((2,2))
t2

tensor([[-1.1224,  0.0312],
        [-0.6804,  0.4683]])

[3] 임의의 정수값으로 구성된 3차원 텐서를 아래 조건 만족하도록 생성하세요.
- 조건
    * 형태 : 10행 10열 3개
    * 타입 : 0 ~ 255값 저장되는 최소 크기 타입
    * 생성 후 3개 2D 텐서로 분리 저장

In [15]:
# 0 ~ 255 사이의 임의의 정수값으로 3차원 텐서 생성 (형태: 10x10x3)
tensor_3d = torch.randint(0, 256, (10, 10, 3), dtype=torch.uint8)

# 3차원 텐서에서 각 2D 텐서를 분리
tensor_2d_1 = tensor_3d[:, :, 0]  # 첫 번째 채널 (10x10)
tensor_2d_2 = tensor_3d[:, :, 1]  # 두 번째 채널 (10x10)
tensor_2d_3 = tensor_3d[:, :, 2]  # 세 번째 채널 (10x10)

# 결과 출력
print("3D Tensor (10x10x3):")
print(tensor_3d)
print("\n2D Tensor 1 (10x10):")
print(tensor_2d_1)
print("\n2D Tensor 2 (10x10):")
print(tensor_2d_2)
print("\n2D Tensor 3 (10x10):")
print(tensor_2d_3)

3D Tensor (10x10x3):
tensor([[[ 70, 160, 252],
         [ 98,  34,  64],
         [ 42,  30,  82],
         [187, 106,  84],
         [150, 114, 153],
         [  5, 119, 136],
         [232,  55,  78],
         [231,  61, 137],
         [210,  59, 142],
         [ 98, 192,  98]],

        [[135, 100,  87],
         [211, 254,  16],
         [221,  26,  98],
         [252,  88, 224],
         [106, 101,  87],
         [  2,  28, 222],
         [208,  47, 214],
         [226, 230, 236],
         [161,  82,  15],
         [ 90, 185,  96]],

        [[151,  16, 251],
         [ 79, 111, 132],
         [211,  31, 108],
         [ 39, 167, 181],
         [109,  12,  41],
         [ 21,  14, 149],
         [240,   4,  69],
         [123, 194, 237],
         [201, 133, 229],
         [ 72, 215, 232]],

        [[234,  53,   9],
         [251, 168,  14],
         [124,  25, 179],
         [224, 121,  92],
         [ 98, 115, 186],
         [226,  56,  77],
         [156, 132, 223],
         [1

[4] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 형변환으로 2D 텐서 생성 T2
- T1의 형변환으로 3D 텐서 생성 T3
- T1의 형변환으로 4D 텐서 생성 T4

In [16]:
# 3의 배수로 구성된 원소 갯수가 12개인 1D 텐서 T1 생성

T1 = torch.arange(3,37,3) 
print(f'T1 :{T1}')

# T1 을 형변환 하여 2D 텐서 T2로 변환 (3X4)

T2 = T1.reshape(3,4) # 3행 4열로 반환
print(f'T2   :{T2}')

# T1을 형변환 하여 3D 텐서 T3로 변환(2x3x3 형태)

T3 = T1.reshape(2,2,3) # 2개의 2X3 배열로 변환

print(f'T3 : {T3}')

T1 :tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])
T2   :tensor([[ 3,  6,  9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36]])
T3 : tensor([[[ 3,  6,  9],
         [12, 15, 18]],

        [[21, 24, 27],
         [30, 33, 36]]])


[5] 아래 2개 텐서에 대한 연산 수행 결과 출력하세요.
- t1 :  [[11,22], [33,44]]
- t2 :  [3,4]
- 연산 : 덧셈, 뺄셈, 곱셈, 나눗셈 연산자와 메서드

In [20]:
# 주어진 텐서
t1 = torch.Tensor([[11,22],[33,44]])
t2 = torch.Tensor([3,4])

print(f'덧셈 :{t1+t2}')
print(f'뺄셈 :{t1-t2}')
print(f'곱셈 :{t1*t2}')
print(f'나눗셈 :{t1/t2}')

덧셈 :tensor([[14., 26.],
        [36., 48.]])
뺄셈 :tensor([[ 8., 18.],
        [30., 40.]])
곱셈 :tensor([[ 33.,  88.],
        [ 99., 176.]])
나눗셈 :tensor([[ 3.6667,  5.5000],
        [11.0000, 11.0000]])


[6] 텐서의 행렬곱 결과 출력
- t1 : 원소 10개
- t2 : 원소 5개
- 연산: 메서드

In [ ]:
# 2x3 크기의 행렬 A
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
# 3x2 크기의 행렬 B
B = torch.tensor([[7, 8], [9, 10], [11, 12]])
# A와 B의 행렬곱
C = torch.matmul(A, B)  # 또는 C = A @ B

print(f'A : {A},\n B : {B},\n C :{C}')

A : tensor([[1, 2, 3],
        [4, 5, 6]]),
 B : tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]),
 C :tensor([[ 58,  64],
        [139, 154]])


[7] 3의 배수로 구성된 원소갯수가 12개인 텐서를 생성하세요.
- 1D 텐서 생성 T1
- T1의 축 추가로 2D 텐서 생성 T2
- T1의 축 추가로 3D 텐서 생성 T3
- T1의 축 추가로 4D 텐서 생성 T4

- T4의 축 축소로 3D 텐서 생성 T5
- T3의 축 축소로 2D 텐서 생성 T6
- T2의 축 축소로 1D 텐서 생성 T7

In [27]:


# 3의 배수로 구성된 12개의 원소를 가진 1D 텐서 생성
T1 = torch.arange(3, 37, 3)  # [3, 6, 9, ..., 36]
print("T1 (1D Tensor):")
print(T1)

# T1의 축 추가로 2D 텐서 생성 (3x4 형태)
T2 = T1.reshape(3, 4)  # 텐서 T1을 (3, 4) 형태로 변환
print("\nT2 (2D Tensor):")
print(T2)

# T1의 축 추가로 3D 텐서 생성 (2x2x3 형태)
T3 = T1.reshape(2, 2, 3)  # 텐서 T1을 (2, 2, 3) 형태로 변환
print("\nT3 (3D Tensor):")
print(T3)

# T1의 축 추가로 4D 텐서 생성 (2x2x2x3 형태)
T4 = T1.reshape(1, 2, 2, 3)  # 텐서 T1을 (2, 2, 2, 3) 형태로 변환
print("\nT4 (4D Tensor):")
print(T4)

# T4의 축 축소로 3D 텐서 생성
T5 = T4.squeeze(3)  # 3번째 축을 제거하여 3D 텐서로 변환
print("\nT5 (3D Tensor):")
print(T5)

# T3의 축 축소로 2D 텐서 생성
T6 = T3.squeeze(2)  # 2번째 축을 제거하여 2D 텐서로 변환
print("\nT6 (2D Tensor):")
print(T6)

# T2의 축 축소로 1D 텐서 생성
T7 = T2.squeeze(1)  # 1번째 축을 제거하여 1D 텐서로 변환
print("\nT7 (1D Tensor):")
print(T7)

T1 (1D Tensor):
tensor([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

T2 (2D Tensor):
tensor([[ 3,  6,  9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36]])

T3 (3D Tensor):
tensor([[[ 3,  6,  9],
         [12, 15, 18]],

        [[21, 24, 27],
         [30, 33, 36]]])

T4 (4D Tensor):
tensor([[[[ 3,  6,  9],
          [12, 15, 18]],

         [[21, 24, 27],
          [30, 33, 36]]]])

T5 (3D Tensor):
tensor([[[[ 3,  6,  9],
          [12, 15, 18]],

         [[21, 24, 27],
          [30, 33, 36]]]])

T6 (2D Tensor):
tensor([[[ 3,  6,  9],
         [12, 15, 18]],

        [[21, 24, 27],
         [30, 33, 36]]])

T7 (1D Tensor):
tensor([[ 3,  6,  9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36]])


[문제 1] torch.arange()를 사용하여 10부터 100까지 5.5 간격으로 생성된 3차원 텐서를 만들어 보세요. 텐서의 형태는 (1, 1, 17)이어야 합니다.

In [29]:
# 1
t1 = torch.arange(10,100,5.5)
print(t1)
t1.reshape(1,1,17)

tensor([10.0000, 15.5000, 21.0000, 26.5000, 32.0000, 37.5000, 43.0000, 48.5000,
        54.0000, 59.5000, 65.0000, 70.5000, 76.0000, 81.5000, 87.0000, 92.5000,
        98.0000])


tensor([[[10.0000, 15.5000, 21.0000, 26.5000, 32.0000, 37.5000, 43.0000,
          48.5000, 54.0000, 59.5000, 65.0000, 70.5000, 76.0000, 81.5000,
          87.0000, 92.5000, 98.0000]]])

[문제 2] 평균이 0이고 표준편차가 1인 정규분포를 따르는 2D 텐서를 생성하고, 랜덤값이 매번 동일하게 생성되도록 설정해 보세요.

In [30]:
#2.
torch.manual_seed(0) # 랜덤시드
tensor_normal = torch.randn(2,3)
print(tensor_normal)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])


[문제 3] 크기가 (3, 3)인 텐서를 생성하고, 이 텐서의 모든 요소에 5를 더하는 연산을 수행해 보세요.

In [35]:
t3 = torch.ones(3,3)
print(t3)

t3 = t3+5
print(t3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


[문제 4] 2개의 텐서를 생성하고, 두 텐서의 덧셈을 수행해 보세요. 텐서 크기는 각각 (3, 3)입니다.

In [ ]:
t1 = torch.Tensor([[2, 2, 1], [3, 3, 1], [4, 4, 1]])
torch.manual_seed(0)
t2 = torch.arange(2, 11, 1)
t2 = t2.reshape(3, 3)

# torch.arange로 더 많은 값을 생성하여 크기 맞추기: 만약 (3, 3) 형태로 변형하려면, torch.arange로 9개의 요소를 생성해야 합니다

# 덧셈 연산
result = t1 + t2

print(t1.size())  # 텐서 t1의 크기 출력
print(t2.size())         # 텐서 t2 출력
print(result)     # 덧셈 결과 출력

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[ 4.,  5.,  5.],
        [ 8.,  9.,  8.],
        [12., 13., 11.]])
