# 사용자 정의 데이터셋(Custom Dataset) <hr>

* torch.utils.data.Dataset 을 상속받아 직접 커스텀 데이터셋 생성
* torch.utils.data.Dataset 은 미완성 추상클래스(Abstract Class)
	* 반드시 구현해야 하는 매서드 존재
	* def _ _ init _ _ (self) : 데이터셋 전처리/ 초기화 메서드
	* def _ _ len _ _ (self) : 데이터셋 길이 즉 샘플 수 반환 메서드
	* def _ _ getiem _ _ (self,idx) : idx 해당 데이터 1개 반환하는 메서드

In [ ]:
# 모듈 로딩 ------------------
import torch								# 텐서 및 기본 텐서 제어 함수들 모듈
import torch.nn.functional as F				# 인공신경망 관련 모듈 
from  torch.utils.data import Dataset		# 인공신경망 데이터 관련 클래스 및 함수들 
from  torch.utils.data import DataLoader	# 인공신경망 데이터 관련 클래스 및 함수들

In [ ]:
# Custom Dataset 생성 
class CustomDataset(Dataset):
	# 초기화 
	def __init__(self):
		print('__init__')
		self.X_data = [[73,80,75],
					  [93,88,93],
					  [89,91,90],
					  [96,98,100],
					  [73,66,70]]
		self.y_data = [[152],[185],[180],[196],[142]]
	
	# 총 데이터 개수 
	def __len__(self):
		print('__len__')

		return len(self.X_data)
	
	def __getitem__(self, idx):
		print('__getitem__')
		x = torch.FloatTensor(self.X_data[idx])
		y = torch.FloatTensor(self.y_data[idx])
		return x,y

In [3]:
# Dataset 객체 생성 --------------------

dataset = CustomDataset()

__init__


In [4]:
# Dataset 객체 확인
len(dataset)

__len__


5

In [5]:
# Dataset 객체확인
print('원소갯수 ', len(dataset))
print('1번 원소/원소', dataset[1])

__len__
원소갯수  5
__getitem__
1번 원소/원소 (tensor([93., 88., 93.]), tensor([185.]))


[2] DataLoader 로 데이터 로딩 <hr>

In [6]:
dLoader = DataLoader(dataset,				# 학습에 사용할 데이터셋 객체
					  batch_size=3, 		# 한번에 학습할 데이터 갯수
					  shuffle=True)			# 데이터셋 섞기

__len__
__len__


In [7]:
# DataLoader 객체 속성
# 한번에 학습할 데이터 양
dLoader.batch_size 

3

In [8]:
# 학습에 사용할 데이터셋 
dLoader.dataset.y_data

[[152], [185], [180], [196], [142]]

In [ ]:
# 데이터 추출

for feature, label in dLoader :
	print(feature, label, sep='\n')
	print('='*50)

__len__
__len__
__getitem__
__getitem__
__getitem__
tensor([[ 73.,  80.,  75.],
        [ 96.,  98., 100.],
        [ 93.,  88.,  93.]])
tensor([[152.],
        [196.],
        [185.]])
__len__
__getitem__
__getitem__
tensor([[89., 91., 90.],
        [73., 66., 70.]])
tensor([[180.],
        [142.]])


: 