# 패션 MINST 모델 & Matricls

- [1] 모듈로딩 및  데이터준비
- [2] 데이터 확인
- [3] 데이터 전처리 => 타겟/피쳐
- [4] 데이터 전용 데이터셋 클래스 설계 & 확인
- [5] 모델 클래스 설계 & 확인
- [6] 학습 준비
- [7] 학습
- [8] 결과확인

In [151]:
# 모듈 로딩

import torch 
import pandas as pd
import numpy as np

import torch.nn as nn 			# Tensor 및 기본 함수들 관련 모듈들
import torch.nn.functional as F # 인공신경망 관련 함수들
import torch.optim as optim 	# 최적화 모듈

from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset,DataLoader

from torchmetrics.classification import * # 성능지표

In [152]:

train_DF = pd.read_csv('../Data/fashion-mnist_train.csv')
test_DF = pd.read_csv('../Data/fashion-mnist_test.csv')



In [153]:
print(train_DF.shape,test_DF.shape)

(60000, 785) (10000, 785)


In [154]:
train_DF.info()
train_DF.label.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to pixel784
dtypes: int64(785)
memory usage: 359.3 MB


array([2, 9, 6, 0, 3, 4, 5, 8, 7, 1])

In [155]:
train_x = train_DF.loc[:,'pixel1':]
train_y =train_DF['label'] 

test_x = test_DF.loc[:,'pixel1':]
test_y =test_DF['label'] 

In [156]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)

(60000, 784) (60000,)
(10000, 784) (10000,)


In [157]:
train_x = train_x/255
test_x = train_x/255

In [158]:

train_DF.iloc[:,0]

0        2
1        9
2        6
3        0
4        3
        ..
59995    9
59996    1
59997    8
59998    8
59999    7
Name: label, Length: 60000, dtype: int64

In [159]:
target = train_DF.iloc[:,0]
label = np.array(target)
label

array([2, 9, 6, ..., 8, 8, 7])

In [ ]:
class train_Dataset(Dataset):
	def __init__(self,train_DF):
		self.feature = train_DF.iloc[:,1:]
		self.target = train_DF.iloc[:,0]

		self.labels = np.array(self.target)
		self.imgs  = np.array(self.feature).reshape(-1, IMAGE_SIZE, IMAGE_SIZE, CHANNEL).astype('float32')
        # 이미지를 (28, 28, 1) 형태로 reshape
	def __len__(self):
		return len(self.target)
		
	def __getitem__(self,idx):	
		label, img = self.labels[idx], self.imgs[idx]
		return torch.LongTensor([label]), torch.FloatTensor(img)
		

In [161]:
class test_Dataset:
	def __init__(self,test_DF):
		self.feature = test_DF.iloc[:,1:]
	
		
		self.imgs  = np.array(self.feature).reshape(-1, IMAGE_SIZE, IMAGE_SIZE, CHANNEL).astype('float32')
		# 이미지를 (28, 28, 1) 형태로 reshape


	def __len__(self):
		return test_DF.shape[0]
		
	def __getitem__(self,idx):	
		img = self.imgs[idx]
		return torch.FloatTensor(img)

In [162]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [163]:
IMAGE_SIZE = 28
CHANNEL = 1
Train_dataset = train_Dataset(train_DF)
Test_dataset = test_Dataset(test_DF)

Train_dataset[0][0] ,Train_dataset[1][0]

(tensor([2]), tensor([9]))

In [174]:
train_DL = DataLoader(dataset=Train_dataset, batch_size=3,shuffle=True)
test_DL = DataLoader(dataset=Test_dataset,batch_size=3)


for label, img in train_DL:
	print(label)
	print(img)
	break



tensor([[2],
        [5],
        [3]])
tensor([[[[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         ...,

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          ...,
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
       

# 모델설계

In [ ]:
# ===============================================================
# 다중분류용 모델
# 클레스 이름 : My_Model
# 부모클래스 : nn.Module
# 모델층 구분 :  입력신호/ 		출력호수/퍼셉트론수			활성화함수
# - 입력층	  :  784				512						ReLu
# - 은닉층	  :  512				128						ReLu
# - 은닉층	  :  128				64						ReLu
# - 은닉층	  :   64				32						ReLu
# - 출력층	  :   32				10						-


class My_Model(nn.module):
	# 모델층 설계 및 초기화
	def __init__(self):
		super.__init__()
		self.in_layer = nn.Linear(784,512)
		self.hd_layer1 = nn.Linear(512,128)
		self.hd_layer2 = nn.Linear(128,64)
		self.hd_layer3 = nn.Linear(64,32)
		self.out_layer = nn.Linear(32,10)

	def forward(input_data):
		out = self.in_layer(input_data)
		
	



	