### [ Numpy ndarray 의 형태 shape 형태]
-	shape 변환 : 원소 갯수 유지, 형태만 1D	=> nD 변경
- 	함수 : numpy.reshape()
-	메서드 : ndarray.reshape()

In [2]:
# 모듈 로딩
import numpy as np

In [3]:
# ndarray 객체 생성
n1 = np.array([[11,22],[33,44],[55,66]])
n1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [7]:
# 2D ==> 3D : 원소 갯수는 유지됨
# reshape( shape 정보)
n1.reshape(1,3,2)

array([[[11, 22],
        [33, 44],
        [55, 66]]])

In [ ]:
# 2D ==> 3D : 원소 갯수는 유지 됨
n1.reshape(1,2,3)

In [ ]:
n1.reshape(1,2,3) # 1 * 2 * 3 ==. 원래 원소 갯수

array([[[11, 22, 33],
        [44, 55, 66]]])

In [11]:
n1.reshape(3,1,-1) # 3*1*? ==> 원래 원소 갯수

array([[[11, 22]],

       [[33, 44]],

       [[55, 66]]])

In [17]:
n3 = n1.reshape(6,1,-1)
print('n3 =>',n3.ndim, n3.shape,n3.data, n3.strides)
print('n1 =>',n1.ndim, n1.shape,n1.data, n1.strides)

n3 => 3 (6, 1, 1) <memory at 0x00000203262D7400> (8, 8, 8)
n1 => 2 (3, 2) <memory at 0x0000020326278EE0> (16, 8)


-	함수: numpy.resize()
-	메서드: ndarray.resize()

In [20]:
n1.resize((1,6))
n1

array([[11, 22, 33, 44, 55, 66]])

In [21]:
n1.resize(6,1)
n1

array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]])

In [ ]:
# -> 원소 갯수 변경
n1.resize(6,2, refcheck=False) 
n1

array([[11, 22],
       [33, 44],
       [55, 66],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])