# 파이토치 의 아키텍쳐

-	크게 세 개의 계층으로 나누어 설명할수있다.
-	가장 상위 파이토치 API
-	파이토치 엔진
	- 다차원 텐서 및 자동 미분 을 처리
- 텐서에 대한 연산 CPU/GPU 를 이용하는 텐서의 실질적인 계산을 위한
	C,CUDA 등 라이브러리
		

* 파이토치 API
	-	torch: GPU 를 지원하는 텐서 패키지
		* 다차원 텐서를 기반으로 다양한 수학적 연산이 가능하도록 특히 CPU 뿐만 아니라
			GPU 에서 연산이 가능하므로 빠른 속도로 많은 양
	
	-	torch.autograd: 자동 미분 패키지
		* Autograd 는 텐서플로, 카페, CNTK 같은 다른 딥러닝 프레임워크 와 가장 차별패키지
			미분 계산을 효율적으로 처리
	
	-	torch.nn : 신경망 구축 및 훈련 패키지
		* 합성곱 신경망, 순환 신경망, 정규화 등이 포함되어 손쉽게 신경망을 구축하고 학습가능
	
	-	torch.multiprocessing : 파이썬 멀티프로세싱 패키지
		* 파이토치에서 사용하는 프로세스 전반에 걸쳐 텐서의 메모리 공유가 가능
	
	- 	torch.utils : DataLoader 및 기타 유틸리티를 제공하는 패키지
		* 모델에 데이터를 제공하기 위한 torch.utils.data.DataLoader 모듈을 주로 사용
			병목 현상을 디버깅 하기 위한 torch.utils.bottleneck, 
			모델 또는 모델의 일부를 검사하기 위한 torch.utils.checkpoint 등의 모듈


# 파이토치 엔진

# 파이토치 기초

nummpy 와 닮은 파이토치 (pythorch)

In [1]:
import torch
a = torch.tensor([1,2,3,4]) # list 가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

b = torch.tensor([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [3]:
A = torch.tensor([[1,2,3],[3,4,5]])

#A = torch.tensor([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야함pr
print(A)
print(A.shape)
print(A.ndim)	#  차원의 수 
print(A.numel()) # 전체 성분의 수

tensor([[1, 2, 3],
        [3, 4, 5]])
torch.Size([2, 3])
2
6


In [5]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3,3))
print(torch.arange(3,10,2))  # range 랑 같은데 tensor 로 만들어줌
print(torch.arange(0,1,0.1)) 	# 소수점 가능
print(torch.linspace(0,1,10)) # 0 에서 부터 1 포함 10개로


tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [7]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a+b
print(c)

tensor([5, 7, 9])


In [8]:
A = torch.tensor([[1,2,3],[1,2,3]])
B = torch.tensor([[4,5,6],[1,1,1]])

C = A+B
D = A-B

print(C)
print(D)
print()

print(A*B)  # 곱셈
print(A/B)	# 나눗셈
print(B**2) # 제곱

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [9]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


# pytorch의 인덱싱 과 슬라이싱

In [10]:
a = torch.tensor([1,2,3,4,5,6,7,8,9])
# 인덱싱 과 슬라이싱
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])


tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
# 행렬에 대한 인덱싱 과 슬라이싱
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2])

B = [[1,2,3,4],[5,6,7,8]]
print(B[0][2])
print(A[1,:]) # 1행, 전부
print(A[1,0:3:2]) 
print(A[:,2]) # 전부, 2번째 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [13]:
# 3차원 행렬 인덱싱
A = torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])

print(A)
print(A[0,1,2])
a = torch.tensor([1,2,3,4]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor(6)
torch.Size([4])
