# [Gray Image Calssification Model]
- 데이터셋 : cat_dog.csv
- 피쳐 70870 => 4900
- x타겟 'cat''god' => 2진 분류
- 학습 : 지도 학습 +


In [284]:
#[1-1] 모듈 로딩
import pandas as pd
import numpy as np

# 학습용/테스트용 데이터셋 분리
from sklearn.model_selection import train_test_split 
# 타겟/라벨 인코딩용
from sklearn.preprocessing import LabelEncoder

In [285]:
# [1-2] 데이터 준비
IMG_DATA = './cat_dog.csv'

In [286]:
# [1-3] 데이터 로딩
img_df = pd.read_csv(IMG_DATA, header=None)
img_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1711 entries, 0 to 1710
Columns: 5626 entries, 0 to 5625
dtypes: int64(5625), object(1)
memory usage: 73.4+ MB


# [2] 이미지 데이터 전처리 <hr> 

In [287]:
# [2-1] 피쳐 와 타겟 분리
img_df.head()

0     1     2     3     4     5     ...  5620  5621  5622  5623  5624  5625
0  cat   251   246   254   249   244  ...    65    58    53    57    62    67
1  cat   251   246   254   249   244  ...    65    58    53    57    62    67
2  cat    58    58    57    56    56  ...    12    10    13    13    13    22
3  cat   159   161   163   166   169  ...   121   131   129   123   117   117
4  cat    30    28    26    27    30  ...   154   179   169   163   163   151

[5 rows x 5626 columns]

In [288]:
# 타겟 추출
target_SR = img_df[0]
target_SR

# 피쳐 추출
# 2 차원
feature_DF = img_df[img_df.columns[1:]]

print(f' feature_DF : {feature_DF.shape}, tarfet_SR: {target_SR.shape}')

 feature_DF : (1711, 5625), tarfet_SR: (1711,)


In [289]:
# [2-2] 피쳐에 대한 전처리 => 이미지 상관관계 X, 데이터 타입, 값의 범위 맞추기
# 0~255  ==> 0.0 ~ 1.0 정규화
# => csv 파일에서 이미지 로딩 => st ==> unit8 
feature_DF = feature_DF.astype('uint8')
feature_DF.dtypes

1       uint8
2       uint8
3       uint8
4       uint8
5       uint8
        ...  
5621    uint8
5622    uint8
5623    uint8
5624    uint8
5625    uint8
Length: 5625, dtype: object

In [290]:
feature_DF.values

array([[251, 246, 254, ...,  57,  62,  67],
       [251, 246, 254, ...,  57,  62,  67],
       [ 58,  58,  57, ...,  13,  13,  22],
       ...,
       [230, 236, 233, ..., 229, 229, 229],
       [ 49,  34,  35, ..., 119,  73,  83],
       [223, 223, 224, ..., 226, 226, 228]], dtype=uint8)

In [291]:
# => 0 ~ 255 : 0.0 ~ 1.0 정규화
feature_DF = feature_DF/255.
feature_DF

1         2         3     ...      5623      5624      5625
0     0.984314  0.964706  0.996078  ...  0.223529  0.243137  0.262745
1     0.984314  0.964706  0.996078  ...  0.223529  0.243137  0.262745
2     0.227451  0.227451  0.223529  ...  0.050980  0.050980  0.086275
3     0.623529  0.631373  0.639216  ...  0.482353  0.458824  0.458824
4     0.117647  0.109804  0.101961  ...  0.639216  0.639216  0.592157
...        ...       ...       ...  ...       ...       ...       ...
1706  0.474510  0.474510  0.478431  ...  0.415686  0.423529  0.427451
1707  0.180392  0.180392  0.180392  ...  0.498039  0.462745  0.454902
1708  0.901961  0.925490  0.913725  ...  0.898039  0.898039  0.898039
1709  0.192157  0.133333  0.137255  ...  0.466667  0.286275  0.325490
1710  0.874510  0.874510  0.878431  ...  0.886275  0.886275  0.894118

[1711 rows x 5625 columns]

In [292]:
# [2-3] 타겟에 대한 전처리 => str/object 타입의 경우 수치화 인코딩

target_EN = LabelEncoder()
target_EN.fit(target_SR)
target_SR = target_EN.transform(target_SR)

In [293]:
# -인코딩 된 정보
target_EN.classes_

array(['Dog', 'cat', 'dog', 'gra'], dtype=object)

In [294]:
 # -타겟 데이터 확인
target_SR

array([1, 1, 1, ..., 0, 2, 0])

In [295]:
# 타겟 데이터 확인
print('타겟의 고유값', np.unique_values(target_SR))

타겟의 고유값 [0 1 2 3]


# [학습 준비] <hr>

In [296]:
# 학습용/테스트용 데이터셋 준비

X_train, X_test, y_train,y_test = train_test_split(feature_DF,
													target_SR,
													test_size=0.2,
													random_state=42,
													stratify=target_SR) # 분류의 경우 타겟 클래스 비율 유지 설정



In [297]:
# 확인
print('[Train]', X_train.shape, y_train.shape)
print('[Test]', X_test.shape, y_test.shape)

[Train] (1368, 5625) (1368,)
[Test] (343, 5625) (343,)


# [4] 학습 진행 <hr>

In [298]:
## [4-1] 분류 모델 관련 모듈로딩

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [299]:
# [4-2] 모델별 학습 진행

lr_model = LogisticRegression(max_iter=10000)
lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [300]:
# [5-1] 분류 모델 관련 검증 모델
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

# 손실/비용 함수 : 손실계산  정답-예측 차이
from sklearn.metrics import log_loss


In [303]:
# [5-2] 검증 진행 ==> 정답 - 예측
result_df = pd.DataFrame(columns=['model','kind','accuray','precision','recall','f1','loss'])

for kind, data, y_true in [('Train',X_train, y_train),('Test',X_test,y_test)]:
	pre_y = lr_model.predict(data)

	print(pre_y.shape, data.shape)
	print(pre_y)
	# 성능평가 : 정답 (1)  == 예측(1)  O, 정답 1 != 예측 (0) , X
	# 정확도
	accuracy = accuracy_score(y_true, pre_y)
	# 정밀도
	precision = precision_score(y_true, pre_y)
	# 재현율
	recall = recall_score(y_true, pre_y)
	# 확률 => 클래스
	f1 = f1_score(y_true, pre_y)

	# -손실/비용 계산 : 정답 1  ---> 1일 확률 0.23 : 1 - 0.23 = 0.77
	proba_y = lr_model.predict_proba(data)
	loss = log_loss(y_true,proba_y)

	# 결과 DataFrame 에 저장
	model_name = lr_model.__class__.__name__
	print(model_name)

	# 

	result_df.loc[result_df.shape[0]+1] = [model_name, kind, accuracy,precision,recall,f1,loss]

	# 전체 결과 출력
	print(f'accuracy : {accuracy:.4f} precision : {precision:.4f}, recall : {recall:.4f}, f1 : {f1:.4f}')
	print(f'loss : {loss:.4f}')
	

(1368,) (1368, 5625)
[1 1 1 ... 2 2 1]


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
result_df

model   kind   accuray  precision    recall        f1      loss
1  LogisticRegression  Train  1.000000   1.000000  1.000000  1.000000  0.077070
2  LogisticRegression   Test  0.637681   0.677419  0.583333  0.626866  0.725723